
package cn.gov.laho.fgk.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Nov 07 16:38:38 CST 2014
 * Generated source version: 2.2.10
 * 
 */

public final class SearchServicePortType_SearchServiceHttpSoap11Endpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.fgk.com", "searchService");

    private SearchServicePortType_SearchServiceHttpSoap11Endpoint_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SearchService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SearchService ss = new SearchService(wsdlURL, SERVICE_NAME);
        SearchServicePortType port = ss.getSearchServiceHttpSoap11Endpoint();  
        
        {
        System.out.println("Invoking fullTextSearchFileInfo...");
        java.lang.String _fullTextSearchFileInfo_args0 = "_fullTextSearchFileInfo_args0715632532";
        java.lang.String _fullTextSearchFileInfo_args1 = "_fullTextSearchFileInfo_args1121319624";
        java.lang.String _fullTextSearchFileInfo_args2 = "_fullTextSearchFileInfo_args21605333706";
        java.lang.Integer _fullTextSearchFileInfo_args3 = Integer.valueOf(-526567543);
        java.lang.Integer _fullTextSearchFileInfo_args4 = Integer.valueOf(-373151512);
        java.lang.Integer _fullTextSearchFileInfo_args5 = Integer.valueOf(2001513904);
        java.lang.Integer _fullTextSearchFileInfo_args6 = Integer.valueOf(-380098078);
        java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _fullTextSearchFileInfo__return = port.fullTextSearchFileInfo(_fullTextSearchFileInfo_args0, _fullTextSearchFileInfo_args1, _fullTextSearchFileInfo_args2, _fullTextSearchFileInfo_args3, _fullTextSearchFileInfo_args4, _fullTextSearchFileInfo_args5, _fullTextSearchFileInfo_args6);
        System.out.println("fullTextSearchFileInfo.result=" + _fullTextSearchFileInfo__return);


        }
        {
        System.out.println("Invoking searchFileInfoTotal...");
        java.lang.String _searchFileInfoTotal_args0 = "_searchFileInfoTotal_args0-2026364982";
        java.lang.Long _searchFileInfoTotal__return = port.searchFileInfoTotal(_searchFileInfoTotal_args0);
        System.out.println("searchFileInfoTotal.result=" + _searchFileInfoTotal__return);


        }
        {
        System.out.println("Invoking advancedSearchFileInfo...");
        java.lang.String _advancedSearchFileInfo_args0 = "_advancedSearchFileInfo_args0-1595325755";
        java.lang.String _advancedSearchFileInfo_args1 = "_advancedSearchFileInfo_args1-1406855265";
        java.lang.String _advancedSearchFileInfo_args2 = "_advancedSearchFileInfo_args2119193287";
        java.lang.String _advancedSearchFileInfo_args3 = "_advancedSearchFileInfo_args3-788997314";
        java.lang.String _advancedSearchFileInfo_args4 = "_advancedSearchFileInfo_args4-119027057";
        java.lang.String _advancedSearchFileInfo_args5 = "_advancedSearchFileInfo_args5-931056998";
        java.lang.String _advancedSearchFileInfo_args6 = "_advancedSearchFileInfo_args6-388044489";
        java.lang.Integer _advancedSearchFileInfo_args7 = Integer.valueOf(1449232541);
        java.lang.Integer _advancedSearchFileInfo_args8 = Integer.valueOf(966070740);
        java.lang.Integer _advancedSearchFileInfo_args9 = Integer.valueOf(64768733);
        java.lang.Integer _advancedSearchFileInfo_args10 = Integer.valueOf(-1617945206);
        java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _advancedSearchFileInfo__return = port.advancedSearchFileInfo(_advancedSearchFileInfo_args0, _advancedSearchFileInfo_args1, _advancedSearchFileInfo_args2, _advancedSearchFileInfo_args3, _advancedSearchFileInfo_args4, _advancedSearchFileInfo_args5, _advancedSearchFileInfo_args6, _advancedSearchFileInfo_args7, _advancedSearchFileInfo_args8, _advancedSearchFileInfo_args9, _advancedSearchFileInfo_args10);
        System.out.println("advancedSearchFileInfo.result=" + _advancedSearchFileInfo__return);


        }
        {
        System.out.println("Invoking searchFileInfo...");
        java.lang.String _searchFileInfo_args0 = "_searchFileInfo_args0-591117473";
        java.lang.Integer _searchFileInfo_args1 = Integer.valueOf(-1792622213);
        java.lang.Integer _searchFileInfo_args2 = Integer.valueOf(200792575);
        java.lang.Integer _searchFileInfo_args3 = Integer.valueOf(-143837945);
        java.lang.Integer _searchFileInfo_args4 = Integer.valueOf(-522631295);
        java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _searchFileInfo__return = port.searchFileInfo(_searchFileInfo_args0, _searchFileInfo_args1, _searchFileInfo_args2, _searchFileInfo_args3, _searchFileInfo_args4);
        System.out.println("searchFileInfo.result=" + _searchFileInfo__return);


        }
        {
        System.out.println("Invoking advancedSearchFileInfoTotal...");
        java.lang.String _advancedSearchFileInfoTotal_args0 = "_advancedSearchFileInfoTotal_args0-17814468";
        java.lang.String _advancedSearchFileInfoTotal_args1 = "_advancedSearchFileInfoTotal_args1-212477356";
        java.lang.String _advancedSearchFileInfoTotal_args2 = "_advancedSearchFileInfoTotal_args2-2126919822";
        java.lang.String _advancedSearchFileInfoTotal_args3 = "_advancedSearchFileInfoTotal_args3-1012068984";
        java.lang.String _advancedSearchFileInfoTotal_args4 = "_advancedSearchFileInfoTotal_args4-2053122989";
        java.lang.String _advancedSearchFileInfoTotal_args5 = "_advancedSearchFileInfoTotal_args51031433362";
        java.lang.String _advancedSearchFileInfoTotal_args6 = "_advancedSearchFileInfoTotal_args6-1338832407";
        java.lang.Long _advancedSearchFileInfoTotal__return = port.advancedSearchFileInfoTotal(_advancedSearchFileInfoTotal_args0, _advancedSearchFileInfoTotal_args1, _advancedSearchFileInfoTotal_args2, _advancedSearchFileInfoTotal_args3, _advancedSearchFileInfoTotal_args4, _advancedSearchFileInfoTotal_args5, _advancedSearchFileInfoTotal_args6);
        System.out.println("advancedSearchFileInfoTotal.result=" + _advancedSearchFileInfoTotal__return);


        }
        {
        System.out.println("Invoking fullTextSearchFileInfoTotal...");
        java.lang.String _fullTextSearchFileInfoTotal_args0 = "_fullTextSearchFileInfoTotal_args0-813325627";
        java.lang.String _fullTextSearchFileInfoTotal_args1 = "_fullTextSearchFileInfoTotal_args1-857532305";
        java.lang.String _fullTextSearchFileInfoTotal_args2 = "_fullTextSearchFileInfoTotal_args2-1074809930";
        java.lang.Long _fullTextSearchFileInfoTotal__return = port.fullTextSearchFileInfoTotal(_fullTextSearchFileInfoTotal_args0, _fullTextSearchFileInfoTotal_args1, _fullTextSearchFileInfoTotal_args2);
        System.out.println("fullTextSearchFileInfoTotal.result=" + _fullTextSearchFileInfoTotal__return);


        }

        System.exit(0);
    }

}
