
package cn.gov.laho.fgk.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Nov 07 16:38:38 CST 2014
 * Generated source version: 2.2.10
 * 
 */

public final class SearchServicePortType_SearchServiceHttpSoap12Endpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.fgk.com", "searchService");

    private SearchServicePortType_SearchServiceHttpSoap12Endpoint_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SearchService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SearchService ss = new SearchService(wsdlURL, SERVICE_NAME);
        SearchServicePortType port = ss.getSearchServiceHttpSoap12Endpoint();  
        
        {
        System.out.println("Invoking fullTextSearchFileInfo...");
        java.lang.String _fullTextSearchFileInfo_args0 = "_fullTextSearchFileInfo_args0-1259618900";
        java.lang.String _fullTextSearchFileInfo_args1 = "_fullTextSearchFileInfo_args1-2069130118";
        java.lang.String _fullTextSearchFileInfo_args2 = "_fullTextSearchFileInfo_args2-310330605";
        java.lang.Integer _fullTextSearchFileInfo_args3 = Integer.valueOf(-857895067);
        java.lang.Integer _fullTextSearchFileInfo_args4 = Integer.valueOf(-282532860);
        java.lang.Integer _fullTextSearchFileInfo_args5 = Integer.valueOf(-1974232916);
        java.lang.Integer _fullTextSearchFileInfo_args6 = Integer.valueOf(1123435288);
        java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _fullTextSearchFileInfo__return = port.fullTextSearchFileInfo(_fullTextSearchFileInfo_args0, _fullTextSearchFileInfo_args1, _fullTextSearchFileInfo_args2, _fullTextSearchFileInfo_args3, _fullTextSearchFileInfo_args4, _fullTextSearchFileInfo_args5, _fullTextSearchFileInfo_args6);
        System.out.println("fullTextSearchFileInfo.result=" + _fullTextSearchFileInfo__return);


        }
        {
        System.out.println("Invoking searchFileInfoTotal...");
        java.lang.String _searchFileInfoTotal_args0 = "_searchFileInfoTotal_args0595621340";
        java.lang.Long _searchFileInfoTotal__return = port.searchFileInfoTotal(_searchFileInfoTotal_args0);
        System.out.println("searchFileInfoTotal.result=" + _searchFileInfoTotal__return);


        }
        {
        System.out.println("Invoking advancedSearchFileInfo...");
        java.lang.String _advancedSearchFileInfo_args0 = "_advancedSearchFileInfo_args01267059200";
        java.lang.String _advancedSearchFileInfo_args1 = "_advancedSearchFileInfo_args11735762892";
        java.lang.String _advancedSearchFileInfo_args2 = "_advancedSearchFileInfo_args2-327434723";
        java.lang.String _advancedSearchFileInfo_args3 = "_advancedSearchFileInfo_args3-742906258";
        java.lang.String _advancedSearchFileInfo_args4 = "_advancedSearchFileInfo_args4-153744769";
        java.lang.String _advancedSearchFileInfo_args5 = "_advancedSearchFileInfo_args5-607914490";
        java.lang.String _advancedSearchFileInfo_args6 = "_advancedSearchFileInfo_args61490021789";
        java.lang.Integer _advancedSearchFileInfo_args7 = Integer.valueOf(-1900800386);
        java.lang.Integer _advancedSearchFileInfo_args8 = Integer.valueOf(-640068026);
        java.lang.Integer _advancedSearchFileInfo_args9 = Integer.valueOf(49879456);
        java.lang.Integer _advancedSearchFileInfo_args10 = Integer.valueOf(-1436974438);
        java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _advancedSearchFileInfo__return = port.advancedSearchFileInfo(_advancedSearchFileInfo_args0, _advancedSearchFileInfo_args1, _advancedSearchFileInfo_args2, _advancedSearchFileInfo_args3, _advancedSearchFileInfo_args4, _advancedSearchFileInfo_args5, _advancedSearchFileInfo_args6, _advancedSearchFileInfo_args7, _advancedSearchFileInfo_args8, _advancedSearchFileInfo_args9, _advancedSearchFileInfo_args10);
        System.out.println("advancedSearchFileInfo.result=" + _advancedSearchFileInfo__return);


        }
        {
        System.out.println("Invoking searchFileInfo...");
        java.lang.String _searchFileInfo_args0 = "_searchFileInfo_args0-1081656442";
        java.lang.Integer _searchFileInfo_args1 = Integer.valueOf(138667282);
        java.lang.Integer _searchFileInfo_args2 = Integer.valueOf(-948436864);
        java.lang.Integer _searchFileInfo_args3 = Integer.valueOf(227034836);
        java.lang.Integer _searchFileInfo_args4 = Integer.valueOf(-1317319110);
        java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _searchFileInfo__return = port.searchFileInfo(_searchFileInfo_args0, _searchFileInfo_args1, _searchFileInfo_args2, _searchFileInfo_args3, _searchFileInfo_args4);
        System.out.println("searchFileInfo.result=" + _searchFileInfo__return);


        }
        {
        System.out.println("Invoking advancedSearchFileInfoTotal...");
        java.lang.String _advancedSearchFileInfoTotal_args0 = "_advancedSearchFileInfoTotal_args0-38509585";
        java.lang.String _advancedSearchFileInfoTotal_args1 = "_advancedSearchFileInfoTotal_args11485960689";
        java.lang.String _advancedSearchFileInfoTotal_args2 = "_advancedSearchFileInfoTotal_args2-998038217";
        java.lang.String _advancedSearchFileInfoTotal_args3 = "_advancedSearchFileInfoTotal_args31202887661";
        java.lang.String _advancedSearchFileInfoTotal_args4 = "_advancedSearchFileInfoTotal_args4-269880118";
        java.lang.String _advancedSearchFileInfoTotal_args5 = "_advancedSearchFileInfoTotal_args5-1550620506";
        java.lang.String _advancedSearchFileInfoTotal_args6 = "_advancedSearchFileInfoTotal_args6-490093164";
        java.lang.Long _advancedSearchFileInfoTotal__return = port.advancedSearchFileInfoTotal(_advancedSearchFileInfoTotal_args0, _advancedSearchFileInfoTotal_args1, _advancedSearchFileInfoTotal_args2, _advancedSearchFileInfoTotal_args3, _advancedSearchFileInfoTotal_args4, _advancedSearchFileInfoTotal_args5, _advancedSearchFileInfoTotal_args6);
        System.out.println("advancedSearchFileInfoTotal.result=" + _advancedSearchFileInfoTotal__return);


        }
        {
        System.out.println("Invoking fullTextSearchFileInfoTotal...");
        java.lang.String _fullTextSearchFileInfoTotal_args0 = "_fullTextSearchFileInfoTotal_args0-1261761996";
        java.lang.String _fullTextSearchFileInfoTotal_args1 = "_fullTextSearchFileInfoTotal_args1128062277";
        java.lang.String _fullTextSearchFileInfoTotal_args2 = "_fullTextSearchFileInfoTotal_args2-1320890114";
        java.lang.Long _fullTextSearchFileInfoTotal__return = port.fullTextSearchFileInfoTotal(_fullTextSearchFileInfoTotal_args0, _fullTextSearchFileInfoTotal_args1, _fullTextSearchFileInfoTotal_args2);
        System.out.println("fullTextSearchFileInfoTotal.result=" + _fullTextSearchFileInfoTotal__return);


        }

        System.exit(0);
    }

}
