
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.gov.laho.fgk.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Nov 07 16:38:38 CST 2014
 * Generated source version: 2.2.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "searchService",
                      portName = "searchServiceHttpSoap11Endpoint",
                      targetNamespace = "http://webservice.fgk.com",
                      wsdlLocation = "http://172.30.242.131:8080/fgk/services/searchService?wsdl",
                      endpointInterface = "cn.gov.laho.fgk.webservice.SearchServicePortType")
                      
public class SearchServicePortTypeImpl2 implements SearchServicePortType {

    private static final Logger LOG = Logger.getLogger(SearchServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see cn.gov.laho.fgk.webservice.SearchServicePortType#fullTextSearchFileInfo(java.lang.String  args0 ,)java.lang.String  args1 ,)java.lang.String  args2 ,)java.lang.Integer  args3 ,)java.lang.Integer  args4 ,)java.lang.Integer  args5 ,)java.lang.Integer  args6 )*
     */
    public java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> fullTextSearchFileInfo(java.lang.String args0,java.lang.String args1,java.lang.String args2,java.lang.Integer args3,java.lang.Integer args4,java.lang.Integer args5,java.lang.Integer args6) { 
        LOG.info("Executing operation fullTextSearchFileInfo");
        System.out.println(args0);
        System.out.println(args1);
        System.out.println(args2);
        System.out.println(args3);
        System.out.println(args4);
        System.out.println(args5);
        System.out.println(args6);
        try {
            java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _return = new java.util.ArrayList<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation>();
            cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation _returnVal1 = new cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation();
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1AddTime = null;
            _returnVal1.setAddTime(_returnVal1AddTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1AddUser = null;
            _returnVal1.setAddUser(_returnVal1AddUser);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1ApproveDepartment = null;
            _returnVal1.setApproveDepartment(_returnVal1ApproveDepartment);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1ApproveTime = null;
            _returnVal1.setApproveTime(_returnVal1ApproveTime);
            _returnVal1.setAuditState(Integer.valueOf(-98528063));
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1AuditTime = null;
            _returnVal1.setAuditTime(_returnVal1AuditTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1CorrelationFile = null;
            _returnVal1.setCorrelationFile(_returnVal1CorrelationFile);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1District = null;
            _returnVal1.setDistrict(_returnVal1District);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1EffectiveTime = null;
            _returnVal1.setEffectiveTime(_returnVal1EffectiveTime);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1ExpirationTime = null;
            _returnVal1.setExpirationTime(_returnVal1ExpirationTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileCategory = null;
            _returnVal1.setFileCategory(_returnVal1FileCategory);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileDescription = null;
            _returnVal1.setFileDescription(_returnVal1FileDescription);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileNumber = null;
            _returnVal1.setFileNumber(_returnVal1FileNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FilePromulgationDepartment = null;
            _returnVal1.setFilePromulgationDepartment(_returnVal1FilePromulgationDepartment);
            _returnVal1.setFileState(Integer.valueOf(-266326421));
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileTitle = null;
            _returnVal1.setFileTitle(_returnVal1FileTitle);
            _returnVal1.setFormatState(Integer.valueOf(504284477));
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1HtmlFilePath = null;
            _returnVal1.setHtmlFilePath(_returnVal1HtmlFilePath);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Id = null;
            _returnVal1.setId(_returnVal1Id);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Keywords = null;
            _returnVal1.setKeywords(_returnVal1Keywords);
            _returnVal1.setLawPowerLevel(Integer.valueOf(-1211328746));
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1LocalReferenceNumber = null;
            _returnVal1.setLocalReferenceNumber(_returnVal1LocalReferenceNumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1ModifyTime = null;
            _returnVal1.setModifyTime(_returnVal1ModifyTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1ModifyUser = null;
            _returnVal1.setModifyUser(_returnVal1ModifyUser);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1PdfFilePath = null;
            _returnVal1.setPdfFilePath(_returnVal1PdfFilePath);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1PowerErea = null;
            _returnVal1.setPowerErea(_returnVal1PowerErea);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1PromulgationReferenceNumber = null;
            _returnVal1.setPromulgationReferenceNumber(_returnVal1PromulgationReferenceNumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1PromulgationTime = null;
            _returnVal1.setPromulgationTime(_returnVal1PromulgationTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Remark = null;
            _returnVal1.setRemark(_returnVal1Remark);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Res1 = null;
            _returnVal1.setRes1(_returnVal1Res1);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Res2 = null;
            _returnVal1.setRes2(_returnVal1Res2);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Res3 = null;
            _returnVal1.setRes3(_returnVal1Res3);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1SrcFilePath = null;
            _returnVal1.setSrcFilePath(_returnVal1SrcFilePath);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Summary = null;
            _returnVal1.setSummary(_returnVal1Summary);
            _returnVal1.setValidityState(Integer.valueOf(588399099));
            _return.add(_returnVal1);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.fgk.webservice.SearchServicePortType#searchFileInfoTotal(java.lang.String  args0 )*
     */
    public java.lang.Long searchFileInfoTotal(java.lang.String args0) { 
        LOG.info("Executing operation searchFileInfoTotal");
        System.out.println(args0);
        try {
            java.lang.Long _return = Long.valueOf(7888987132440665565l);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.fgk.webservice.SearchServicePortType#advancedSearchFileInfo(java.lang.String  args0 ,)java.lang.String  args1 ,)java.lang.String  args2 ,)java.lang.String  args3 ,)java.lang.String  args4 ,)java.lang.String  args5 ,)java.lang.String  args6 ,)java.lang.Integer  args7 ,)java.lang.Integer  args8 ,)java.lang.Integer  args9 ,)java.lang.Integer  args10 )*
     */
    public java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> advancedSearchFileInfo(java.lang.String args0,java.lang.String args1,java.lang.String args2,java.lang.String args3,java.lang.String args4,java.lang.String args5,java.lang.String args6,java.lang.Integer args7,java.lang.Integer args8,java.lang.Integer args9,java.lang.Integer args10) { 
        LOG.info("Executing operation advancedSearchFileInfo");
        System.out.println(args0);
        System.out.println(args1);
        System.out.println(args2);
        System.out.println(args3);
        System.out.println(args4);
        System.out.println(args5);
        System.out.println(args6);
        System.out.println(args7);
        System.out.println(args8);
        System.out.println(args9);
        System.out.println(args10);
        try {
            java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _return = new java.util.ArrayList<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation>();
            cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation _returnVal1 = new cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation();
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1AddTime = null;
            _returnVal1.setAddTime(_returnVal1AddTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1AddUser = null;
            _returnVal1.setAddUser(_returnVal1AddUser);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1ApproveDepartment = null;
            _returnVal1.setApproveDepartment(_returnVal1ApproveDepartment);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1ApproveTime = null;
            _returnVal1.setApproveTime(_returnVal1ApproveTime);
            _returnVal1.setAuditState(Integer.valueOf(-1611541649));
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1AuditTime = null;
            _returnVal1.setAuditTime(_returnVal1AuditTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1CorrelationFile = null;
            _returnVal1.setCorrelationFile(_returnVal1CorrelationFile);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1District = null;
            _returnVal1.setDistrict(_returnVal1District);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1EffectiveTime = null;
            _returnVal1.setEffectiveTime(_returnVal1EffectiveTime);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1ExpirationTime = null;
            _returnVal1.setExpirationTime(_returnVal1ExpirationTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileCategory = null;
            _returnVal1.setFileCategory(_returnVal1FileCategory);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileDescription = null;
            _returnVal1.setFileDescription(_returnVal1FileDescription);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileNumber = null;
            _returnVal1.setFileNumber(_returnVal1FileNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FilePromulgationDepartment = null;
            _returnVal1.setFilePromulgationDepartment(_returnVal1FilePromulgationDepartment);
            _returnVal1.setFileState(Integer.valueOf(460331349));
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileTitle = null;
            _returnVal1.setFileTitle(_returnVal1FileTitle);
            _returnVal1.setFormatState(Integer.valueOf(-2056557176));
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1HtmlFilePath = null;
            _returnVal1.setHtmlFilePath(_returnVal1HtmlFilePath);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Id = null;
            _returnVal1.setId(_returnVal1Id);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Keywords = null;
            _returnVal1.setKeywords(_returnVal1Keywords);
            _returnVal1.setLawPowerLevel(Integer.valueOf(970372294));
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1LocalReferenceNumber = null;
            _returnVal1.setLocalReferenceNumber(_returnVal1LocalReferenceNumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1ModifyTime = null;
            _returnVal1.setModifyTime(_returnVal1ModifyTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1ModifyUser = null;
            _returnVal1.setModifyUser(_returnVal1ModifyUser);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1PdfFilePath = null;
            _returnVal1.setPdfFilePath(_returnVal1PdfFilePath);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1PowerErea = null;
            _returnVal1.setPowerErea(_returnVal1PowerErea);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1PromulgationReferenceNumber = null;
            _returnVal1.setPromulgationReferenceNumber(_returnVal1PromulgationReferenceNumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1PromulgationTime = null;
            _returnVal1.setPromulgationTime(_returnVal1PromulgationTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Remark = null;
            _returnVal1.setRemark(_returnVal1Remark);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Res1 = null;
            _returnVal1.setRes1(_returnVal1Res1);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Res2 = null;
            _returnVal1.setRes2(_returnVal1Res2);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Res3 = null;
            _returnVal1.setRes3(_returnVal1Res3);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1SrcFilePath = null;
            _returnVal1.setSrcFilePath(_returnVal1SrcFilePath);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Summary = null;
            _returnVal1.setSummary(_returnVal1Summary);
            _returnVal1.setValidityState(Integer.valueOf(-474040073));
            _return.add(_returnVal1);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.fgk.webservice.SearchServicePortType#searchFileInfo(java.lang.String  args0 ,)java.lang.Integer  args1 ,)java.lang.Integer  args2 ,)java.lang.Integer  args3 ,)java.lang.Integer  args4 )*
     */
    public java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> searchFileInfo(java.lang.String args0,java.lang.Integer args1,java.lang.Integer args2,java.lang.Integer args3,java.lang.Integer args4) { 
        LOG.info("Executing operation searchFileInfo");
        System.out.println(args0);
        System.out.println(args1);
        System.out.println(args2);
        System.out.println(args3);
        System.out.println(args4);
        try {
            java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _return = new java.util.ArrayList<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation>();
            cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation _returnVal1 = new cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation();
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1AddTime = null;
            _returnVal1.setAddTime(_returnVal1AddTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1AddUser = null;
            _returnVal1.setAddUser(_returnVal1AddUser);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1ApproveDepartment = null;
            _returnVal1.setApproveDepartment(_returnVal1ApproveDepartment);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1ApproveTime = null;
            _returnVal1.setApproveTime(_returnVal1ApproveTime);
            _returnVal1.setAuditState(Integer.valueOf(-2060073959));
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1AuditTime = null;
            _returnVal1.setAuditTime(_returnVal1AuditTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1CorrelationFile = null;
            _returnVal1.setCorrelationFile(_returnVal1CorrelationFile);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1District = null;
            _returnVal1.setDistrict(_returnVal1District);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1EffectiveTime = null;
            _returnVal1.setEffectiveTime(_returnVal1EffectiveTime);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1ExpirationTime = null;
            _returnVal1.setExpirationTime(_returnVal1ExpirationTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileCategory = null;
            _returnVal1.setFileCategory(_returnVal1FileCategory);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileDescription = null;
            _returnVal1.setFileDescription(_returnVal1FileDescription);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileNumber = null;
            _returnVal1.setFileNumber(_returnVal1FileNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FilePromulgationDepartment = null;
            _returnVal1.setFilePromulgationDepartment(_returnVal1FilePromulgationDepartment);
            _returnVal1.setFileState(Integer.valueOf(240670298));
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1FileTitle = null;
            _returnVal1.setFileTitle(_returnVal1FileTitle);
            _returnVal1.setFormatState(Integer.valueOf(-1576981391));
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1HtmlFilePath = null;
            _returnVal1.setHtmlFilePath(_returnVal1HtmlFilePath);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Id = null;
            _returnVal1.setId(_returnVal1Id);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Keywords = null;
            _returnVal1.setKeywords(_returnVal1Keywords);
            _returnVal1.setLawPowerLevel(Integer.valueOf(-380221739));
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1LocalReferenceNumber = null;
            _returnVal1.setLocalReferenceNumber(_returnVal1LocalReferenceNumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1ModifyTime = null;
            _returnVal1.setModifyTime(_returnVal1ModifyTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1ModifyUser = null;
            _returnVal1.setModifyUser(_returnVal1ModifyUser);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1PdfFilePath = null;
            _returnVal1.setPdfFilePath(_returnVal1PdfFilePath);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1PowerErea = null;
            _returnVal1.setPowerErea(_returnVal1PowerErea);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1PromulgationReferenceNumber = null;
            _returnVal1.setPromulgationReferenceNumber(_returnVal1PromulgationReferenceNumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnVal1PromulgationTime = null;
            _returnVal1.setPromulgationTime(_returnVal1PromulgationTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Remark = null;
            _returnVal1.setRemark(_returnVal1Remark);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Res1 = null;
            _returnVal1.setRes1(_returnVal1Res1);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Res2 = null;
            _returnVal1.setRes2(_returnVal1Res2);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Res3 = null;
            _returnVal1.setRes3(_returnVal1Res3);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1SrcFilePath = null;
            _returnVal1.setSrcFilePath(_returnVal1SrcFilePath);
            javax.xml.bind.JAXBElement<java.lang.String> _returnVal1Summary = null;
            _returnVal1.setSummary(_returnVal1Summary);
            _returnVal1.setValidityState(Integer.valueOf(768634968));
            _return.add(_returnVal1);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.fgk.webservice.SearchServicePortType#advancedSearchFileInfoTotal(java.lang.String  args0 ,)java.lang.String  args1 ,)java.lang.String  args2 ,)java.lang.String  args3 ,)java.lang.String  args4 ,)java.lang.String  args5 ,)java.lang.String  args6 )*
     */
    public java.lang.Long advancedSearchFileInfoTotal(java.lang.String args0,java.lang.String args1,java.lang.String args2,java.lang.String args3,java.lang.String args4,java.lang.String args5,java.lang.String args6) { 
        LOG.info("Executing operation advancedSearchFileInfoTotal");
        System.out.println(args0);
        System.out.println(args1);
        System.out.println(args2);
        System.out.println(args3);
        System.out.println(args4);
        System.out.println(args5);
        System.out.println(args6);
        try {
            java.lang.Long _return = Long.valueOf(5820282886345473007l);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.fgk.webservice.SearchServicePortType#fullTextSearchFileInfoTotal(java.lang.String  args0 ,)java.lang.String  args1 ,)java.lang.String  args2 )*
     */
    public java.lang.Long fullTextSearchFileInfoTotal(java.lang.String args0,java.lang.String args1,java.lang.String args2) { 
        LOG.info("Executing operation fullTextSearchFileInfoTotal");
        System.out.println(args0);
        System.out.println(args1);
        System.out.println(args2);
        try {
            java.lang.Long _return = Long.valueOf(983006556327678424l);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
