package cn.gov.laho.fgk.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Nov 07 16:38:38 CST 2014
 * Generated source version: 2.2.10
 * 
 */
 
@WebService(targetNamespace = "http://webservice.fgk.com", name = "searchServicePortType")
@XmlSeeAlso({ObjectFactory.class, cn.gov.laho.fgk.webservice.pojo.xsd.ObjectFactory.class})
public interface SearchServicePortType {

    @WebResult(name = "return", targetNamespace = "http://webservice.fgk.com")
    @Action(input = "urn:fullTextSearchFileInfo", output = "urn:fullTextSearchFileInfoResponse")
    @RequestWrapper(localName = "fullTextSearchFileInfo", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.FullTextSearchFileInfo")
    @WebMethod(action = "urn:fullTextSearchFileInfo")
    @ResponseWrapper(localName = "fullTextSearchFileInfoResponse", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.FullTextSearchFileInfoResponse")
    public java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> fullTextSearchFileInfo(
        @WebParam(name = "args0", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args2,
        @WebParam(name = "args3", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args3,
        @WebParam(name = "args4", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args4,
        @WebParam(name = "args5", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args5,
        @WebParam(name = "args6", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args6
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.fgk.com")
    @Action(input = "urn:searchFileInfoTotal", output = "urn:searchFileInfoTotalResponse")
    @RequestWrapper(localName = "searchFileInfoTotal", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.SearchFileInfoTotal")
    @WebMethod(action = "urn:searchFileInfoTotal")
    @ResponseWrapper(localName = "searchFileInfoTotalResponse", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.SearchFileInfoTotalResponse")
    public java.lang.Long searchFileInfoTotal(
        @WebParam(name = "args0", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.fgk.com")
    @Action(input = "urn:advancedSearchFileInfo", output = "urn:advancedSearchFileInfoResponse")
    @RequestWrapper(localName = "advancedSearchFileInfo", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.AdvancedSearchFileInfo")
    @WebMethod(action = "urn:advancedSearchFileInfo")
    @ResponseWrapper(localName = "advancedSearchFileInfoResponse", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.AdvancedSearchFileInfoResponse")
    public java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> advancedSearchFileInfo(
        @WebParam(name = "args0", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args2,
        @WebParam(name = "args3", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args3,
        @WebParam(name = "args4", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args4,
        @WebParam(name = "args5", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args5,
        @WebParam(name = "args6", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args6,
        @WebParam(name = "args7", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args7,
        @WebParam(name = "args8", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args8,
        @WebParam(name = "args9", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args9,
        @WebParam(name = "args10", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args10
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.fgk.com")
    @Action(input = "urn:searchFileInfo", output = "urn:searchFileInfoResponse")
    @RequestWrapper(localName = "searchFileInfo", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.SearchFileInfo")
    @WebMethod(action = "urn:searchFileInfo")
    @ResponseWrapper(localName = "searchFileInfoResponse", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.SearchFileInfoResponse")
    public java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> searchFileInfo(
        @WebParam(name = "args0", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args2,
        @WebParam(name = "args3", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args3,
        @WebParam(name = "args4", targetNamespace = "http://webservice.fgk.com")
        java.lang.Integer args4
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.fgk.com")
    @Action(input = "urn:advancedSearchFileInfoTotal", output = "urn:advancedSearchFileInfoTotalResponse")
    @RequestWrapper(localName = "advancedSearchFileInfoTotal", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.AdvancedSearchFileInfoTotal")
    @WebMethod(action = "urn:advancedSearchFileInfoTotal")
    @ResponseWrapper(localName = "advancedSearchFileInfoTotalResponse", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.AdvancedSearchFileInfoTotalResponse")
    public java.lang.Long advancedSearchFileInfoTotal(
        @WebParam(name = "args0", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args2,
        @WebParam(name = "args3", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args3,
        @WebParam(name = "args4", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args4,
        @WebParam(name = "args5", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args5,
        @WebParam(name = "args6", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args6
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.fgk.com")
    @Action(input = "urn:fullTextSearchFileInfoTotal", output = "urn:fullTextSearchFileInfoTotalResponse")
    @RequestWrapper(localName = "fullTextSearchFileInfoTotal", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.FullTextSearchFileInfoTotal")
    @WebMethod(action = "urn:fullTextSearchFileInfoTotal")
    @ResponseWrapper(localName = "fullTextSearchFileInfoTotalResponse", targetNamespace = "http://webservice.fgk.com", className = "cn.gov.laho.fgk.webservice.FullTextSearchFileInfoTotalResponse")
    public java.lang.Long fullTextSearchFileInfoTotal(
        @WebParam(name = "args0", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.fgk.com")
        java.lang.String args2
    );
}
