
package cn.gov.laho.fgk.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Nov 07 16:38:38 CST 2014
 * Generated source version: 2.2.10
 * 
 */

public final class SearchServicePortType_SearchServiceHttpEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.fgk.com", "searchService");

    private SearchServicePortType_SearchServiceHttpEndpoint_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SearchService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SearchService ss = new SearchService(wsdlURL, SERVICE_NAME);
        SearchServicePortType port = ss.getSearchServiceHttpEndpoint();  
        
        {
        System.out.println("Invoking fullTextSearchFileInfo...");
        java.lang.String _fullTextSearchFileInfo_args0 = "_fullTextSearchFileInfo_args0-654332199";
        java.lang.String _fullTextSearchFileInfo_args1 = "_fullTextSearchFileInfo_args11580085364";
        java.lang.String _fullTextSearchFileInfo_args2 = "_fullTextSearchFileInfo_args2-1513981515";
        java.lang.Integer _fullTextSearchFileInfo_args3 = Integer.valueOf(1811705331);
        java.lang.Integer _fullTextSearchFileInfo_args4 = Integer.valueOf(-1526441659);
        java.lang.Integer _fullTextSearchFileInfo_args5 = Integer.valueOf(1545915140);
        java.lang.Integer _fullTextSearchFileInfo_args6 = Integer.valueOf(1067547830);
        java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _fullTextSearchFileInfo__return = port.fullTextSearchFileInfo(_fullTextSearchFileInfo_args0, _fullTextSearchFileInfo_args1, _fullTextSearchFileInfo_args2, _fullTextSearchFileInfo_args3, _fullTextSearchFileInfo_args4, _fullTextSearchFileInfo_args5, _fullTextSearchFileInfo_args6);
        System.out.println("fullTextSearchFileInfo.result=" + _fullTextSearchFileInfo__return);


        }
        {
        System.out.println("Invoking searchFileInfoTotal...");
        java.lang.String _searchFileInfoTotal_args0 = "_searchFileInfoTotal_args0125876604";
        java.lang.Long _searchFileInfoTotal__return = port.searchFileInfoTotal(_searchFileInfoTotal_args0);
        System.out.println("searchFileInfoTotal.result=" + _searchFileInfoTotal__return);


        }
        {
        System.out.println("Invoking advancedSearchFileInfo...");
        java.lang.String _advancedSearchFileInfo_args0 = "_advancedSearchFileInfo_args01834628696";
        java.lang.String _advancedSearchFileInfo_args1 = "_advancedSearchFileInfo_args1-1089757533";
        java.lang.String _advancedSearchFileInfo_args2 = "_advancedSearchFileInfo_args2-587460677";
        java.lang.String _advancedSearchFileInfo_args3 = "_advancedSearchFileInfo_args32011552572";
        java.lang.String _advancedSearchFileInfo_args4 = "_advancedSearchFileInfo_args41982874034";
        java.lang.String _advancedSearchFileInfo_args5 = "_advancedSearchFileInfo_args51738480129";
        java.lang.String _advancedSearchFileInfo_args6 = "_advancedSearchFileInfo_args6-1880680632";
        java.lang.Integer _advancedSearchFileInfo_args7 = Integer.valueOf(-1696754930);
        java.lang.Integer _advancedSearchFileInfo_args8 = Integer.valueOf(422374884);
        java.lang.Integer _advancedSearchFileInfo_args9 = Integer.valueOf(-1994990369);
        java.lang.Integer _advancedSearchFileInfo_args10 = Integer.valueOf(-2024488405);
        java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _advancedSearchFileInfo__return = port.advancedSearchFileInfo(_advancedSearchFileInfo_args0, _advancedSearchFileInfo_args1, _advancedSearchFileInfo_args2, _advancedSearchFileInfo_args3, _advancedSearchFileInfo_args4, _advancedSearchFileInfo_args5, _advancedSearchFileInfo_args6, _advancedSearchFileInfo_args7, _advancedSearchFileInfo_args8, _advancedSearchFileInfo_args9, _advancedSearchFileInfo_args10);
        System.out.println("advancedSearchFileInfo.result=" + _advancedSearchFileInfo__return);


        }
        {
        System.out.println("Invoking searchFileInfo...");
        java.lang.String _searchFileInfo_args0 = "_searchFileInfo_args0778270660";
        java.lang.Integer _searchFileInfo_args1 = Integer.valueOf(-1231497112);
        java.lang.Integer _searchFileInfo_args2 = Integer.valueOf(854691573);
        java.lang.Integer _searchFileInfo_args3 = Integer.valueOf(-1340088187);
        java.lang.Integer _searchFileInfo_args4 = Integer.valueOf(826081970);
        java.util.List<cn.gov.laho.fgk.webservice.pojo.xsd.FileInfomation> _searchFileInfo__return = port.searchFileInfo(_searchFileInfo_args0, _searchFileInfo_args1, _searchFileInfo_args2, _searchFileInfo_args3, _searchFileInfo_args4);
        System.out.println("searchFileInfo.result=" + _searchFileInfo__return);


        }
        {
        System.out.println("Invoking advancedSearchFileInfoTotal...");
        java.lang.String _advancedSearchFileInfoTotal_args0 = "_advancedSearchFileInfoTotal_args0-336836399";
        java.lang.String _advancedSearchFileInfoTotal_args1 = "_advancedSearchFileInfoTotal_args1124567829";
        java.lang.String _advancedSearchFileInfoTotal_args2 = "_advancedSearchFileInfoTotal_args2-544401368";
        java.lang.String _advancedSearchFileInfoTotal_args3 = "_advancedSearchFileInfoTotal_args3644894579";
        java.lang.String _advancedSearchFileInfoTotal_args4 = "_advancedSearchFileInfoTotal_args4-1101467838";
        java.lang.String _advancedSearchFileInfoTotal_args5 = "_advancedSearchFileInfoTotal_args51144470671";
        java.lang.String _advancedSearchFileInfoTotal_args6 = "_advancedSearchFileInfoTotal_args6-1564833240";
        java.lang.Long _advancedSearchFileInfoTotal__return = port.advancedSearchFileInfoTotal(_advancedSearchFileInfoTotal_args0, _advancedSearchFileInfoTotal_args1, _advancedSearchFileInfoTotal_args2, _advancedSearchFileInfoTotal_args3, _advancedSearchFileInfoTotal_args4, _advancedSearchFileInfoTotal_args5, _advancedSearchFileInfoTotal_args6);
        System.out.println("advancedSearchFileInfoTotal.result=" + _advancedSearchFileInfoTotal__return);


        }
        {
        System.out.println("Invoking fullTextSearchFileInfoTotal...");
        java.lang.String _fullTextSearchFileInfoTotal_args0 = "_fullTextSearchFileInfoTotal_args0-1291807769";
        java.lang.String _fullTextSearchFileInfoTotal_args1 = "_fullTextSearchFileInfoTotal_args1864851492";
        java.lang.String _fullTextSearchFileInfoTotal_args2 = "_fullTextSearchFileInfoTotal_args2-1561434921";
        java.lang.Long _fullTextSearchFileInfoTotal__return = port.fullTextSearchFileInfoTotal(_fullTextSearchFileInfoTotal_args0, _fullTextSearchFileInfoTotal_args1, _fullTextSearchFileInfoTotal_args2);
        System.out.println("fullTextSearchFileInfoTotal.result=" + _fullTextSearchFileInfoTotal__return);


        }

        System.exit(0);
    }

}
