
package cn.gov.laho.gzfgoa.flow.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Nov 07 16:59:04 CST 2014
 * Generated source version: 2.2.10
 * 
 */

public final class ProcInfoServicePortType_ProcInfoServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.flow.gzfg.kwhope.com", "ProcInfoService");

    private ProcInfoServicePortType_ProcInfoServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ProcInfoService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProcInfoService ss = new ProcInfoService(wsdlURL, SERVICE_NAME);
        ProcInfoServicePortType port = ss.getProcInfoServiceHttpPort();  
        
        {
        System.out.println("Invoking queryFlowNum...");
        java.lang.String _queryFlowNum_in0 = "_queryFlowNum_in0-1777789768";
        int _queryFlowNum_in1 = 1395251598;
        int _queryFlowNum_in2 = -10549955;
        java.lang.String _queryFlowNum_in3 = "_queryFlowNum_in3-1517613835";
        java.lang.String _queryFlowNum_in4 = "_queryFlowNum_in4498336087";
        java.lang.String _queryFlowNum_in5 = "_queryFlowNum_in52017208765";
        java.lang.String _queryFlowNum_in6 = "_queryFlowNum_in6-802435060";
        java.lang.String _queryFlowNum_in7 = "_queryFlowNum_in7-776524005";
        java.lang.String _queryFlowNum_in8 = "_queryFlowNum_in81920368427";
        java.lang.String _queryFlowNum_in9 = "_queryFlowNum_in9556484564";
        java.lang.String _queryFlowNum_in10 = "_queryFlowNum_in10-313755326";
        java.lang.String _queryFlowNum_in11 = "_queryFlowNum_in11-325080263";
        java.lang.String _queryFlowNum_in12 = "_queryFlowNum_in121364930362";
        java.lang.String _queryFlowNum_in13 = "_queryFlowNum_in13-943220387";
        int _queryFlowNum__return = port.queryFlowNum(_queryFlowNum_in0, _queryFlowNum_in1, _queryFlowNum_in2, _queryFlowNum_in3, _queryFlowNum_in4, _queryFlowNum_in5, _queryFlowNum_in6, _queryFlowNum_in7, _queryFlowNum_in8, _queryFlowNum_in9, _queryFlowNum_in10, _queryFlowNum_in11, _queryFlowNum_in12, _queryFlowNum_in13);
        System.out.println("queryFlowNum.result=" + _queryFlowNum__return);


        }
        {
        System.out.println("Invoking getQueryFinishProc...");
        java.lang.String _getQueryFinishProc_in0 = "_getQueryFinishProc_in033735331";
        int _getQueryFinishProc_in1 = -219476229;
        int _getQueryFinishProc_in2 = -340543251;
        int _getQueryFinishProc_in3 = 1826318246;
        java.lang.String _getQueryFinishProc_in4 = "_getQueryFinishProc_in41596583209";
        cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _getQueryFinishProc__return = port.getQueryFinishProc(_getQueryFinishProc_in0, _getQueryFinishProc_in1, _getQueryFinishProc_in2, _getQueryFinishProc_in3, _getQueryFinishProc_in4);
        System.out.println("getQueryFinishProc.result=" + _getQueryFinishProc__return);


        }
        {
        System.out.println("Invoking getQueryFinishProcNum...");
        java.lang.String _getQueryFinishProcNum_in0 = "_getQueryFinishProcNum_in0-25433800";
        int _getQueryFinishProcNum_in1 = -2101934844;
        int _getQueryFinishProcNum_in2 = -193908321;
        int _getQueryFinishProcNum_in3 = -1461031145;
        java.lang.String _getQueryFinishProcNum_in4 = "_getQueryFinishProcNum_in4-470071178";
        int _getQueryFinishProcNum__return = port.getQueryFinishProcNum(_getQueryFinishProcNum_in0, _getQueryFinishProcNum_in1, _getQueryFinishProcNum_in2, _getQueryFinishProcNum_in3, _getQueryFinishProcNum_in4);
        System.out.println("getQueryFinishProcNum.result=" + _getQueryFinishProcNum__return);


        }
        {
        System.out.println("Invoking getListRuQingNum...");
        int _getListRuQingNum_in0 = 47428553;
        int _getListRuQingNum_in1 = 1846720520;
        int _getListRuQingNum__return = port.getListRuQingNum(_getListRuQingNum_in0, _getListRuQingNum_in1);
        System.out.println("getListRuQingNum.result=" + _getListRuQingNum__return);


        }
        {
        System.out.println("Invoking getListJianBao...");
        int _getListJianBao_in0 = -1482000563;
        int _getListJianBao_in1 = 682499507;
        cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _getListJianBao__return = port.getListJianBao(_getListJianBao_in0, _getListJianBao_in1);
        System.out.println("getListJianBao.result=" + _getListJianBao__return);


        }
        {
        System.out.println("Invoking getWeiWanDuban...");
        java.lang.String _getWeiWanDuban_in0 = "_getWeiWanDuban_in01794589320";
        java.lang.String _getWeiWanDuban_in1 = "_getWeiWanDuban_in1413804491";
        int _getWeiWanDuban__return = port.getWeiWanDuban(_getWeiWanDuban_in0, _getWeiWanDuban_in1);
        System.out.println("getWeiWanDuban.result=" + _getWeiWanDuban__return);


        }
        {
        System.out.println("Invoking getListProc...");
        java.lang.String _getListProc_in0 = "_getListProc_in0120771038";
        int _getListProc_in1 = -1695053982;
        int _getListProc_in2 = 1797100606;
        int _getListProc_in3 = -127859034;
        java.lang.String _getListProc_in4 = "_getListProc_in4-832241185";
        java.lang.String _getListProc_in5 = "_getListProc_in5-1920579405";
        cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _getListProc__return = port.getListProc(_getListProc_in0, _getListProc_in1, _getListProc_in2, _getListProc_in3, _getListProc_in4, _getListProc_in5);
        System.out.println("getListProc.result=" + _getListProc__return);


        }
        {
        System.out.println("Invoking getListProcNum...");
        java.lang.String _getListProcNum_in0 = "_getListProcNum_in01518588303";
        int _getListProcNum_in1 = 1819198988;
        int _getListProcNum_in2 = -497507198;
        int _getListProcNum_in3 = -1068764905;
        java.lang.String _getListProcNum_in4 = "_getListProcNum_in41544868861";
        java.lang.String _getListProcNum_in5 = "_getListProcNum_in592479565";
        int _getListProcNum__return = port.getListProcNum(_getListProcNum_in0, _getListProcNum_in1, _getListProcNum_in2, _getListProcNum_in3, _getListProcNum_in4, _getListProcNum_in5);
        System.out.println("getListProcNum.result=" + _getListProcNum__return);


        }
        {
        System.out.println("Invoking queryFlow...");
        java.lang.String _queryFlow_in0 = "_queryFlow_in0-159157918";
        int _queryFlow_in1 = -1220511741;
        int _queryFlow_in2 = -1638625193;
        java.lang.String _queryFlow_in3 = "_queryFlow_in3-107568140";
        java.lang.String _queryFlow_in4 = "_queryFlow_in41911581727";
        java.lang.String _queryFlow_in5 = "_queryFlow_in5-170045197";
        java.lang.String _queryFlow_in6 = "_queryFlow_in6779301998";
        java.lang.String _queryFlow_in7 = "_queryFlow_in7-1448210065";
        java.lang.String _queryFlow_in8 = "_queryFlow_in81958746925";
        java.lang.String _queryFlow_in9 = "_queryFlow_in9-345556047";
        java.lang.String _queryFlow_in10 = "_queryFlow_in10-611849202";
        java.lang.String _queryFlow_in11 = "_queryFlow_in111472425717";
        java.lang.String _queryFlow_in12 = "_queryFlow_in12-1032529943";
        java.lang.String _queryFlow_in13 = "_queryFlow_in131875793110";
        int _queryFlow_in14 = 1652457772;
        int _queryFlow_in15 = 550631076;
        cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _queryFlow__return = port.queryFlow(_queryFlow_in0, _queryFlow_in1, _queryFlow_in2, _queryFlow_in3, _queryFlow_in4, _queryFlow_in5, _queryFlow_in6, _queryFlow_in7, _queryFlow_in8, _queryFlow_in9, _queryFlow_in10, _queryFlow_in11, _queryFlow_in12, _queryFlow_in13, _queryFlow_in14, _queryFlow_in15);
        System.out.println("queryFlow.result=" + _queryFlow__return);


        }
        {
        System.out.println("Invoking getListProcInfo...");
        int _getListProcInfo_in0 = -1305768979;
        java.lang.String _getListProcInfo_in1 = "_getListProcInfo_in11734355601";
        cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _getListProcInfo__return = port.getListProcInfo(_getListProcInfo_in0, _getListProcInfo_in1);
        System.out.println("getListProcInfo.result=" + _getListProcInfo__return);


        }
        {
        System.out.println("Invoking getQueryProc...");
        java.lang.String _getQueryProc_in0 = "_getQueryProc_in01010977627";
        int _getQueryProc_in1 = -1355791639;
        int _getQueryProc_in2 = -955093084;
        int _getQueryProc_in3 = 1694488998;
        cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _getQueryProc__return = port.getQueryProc(_getQueryProc_in0, _getQueryProc_in1, _getQueryProc_in2, _getQueryProc_in3);
        System.out.println("getQueryProc.result=" + _getQueryProc__return);


        }
        {
        System.out.println("Invoking getQueryProcNum...");
        java.lang.String _getQueryProcNum_in0 = "_getQueryProcNum_in01365516932";
        int _getQueryProcNum_in1 = -1506386653;
        int _getQueryProcNum_in2 = 1853136416;
        int _getQueryProcNum_in3 = 458520250;
        int _getQueryProcNum__return = port.getQueryProcNum(_getQueryProcNum_in0, _getQueryProcNum_in1, _getQueryProcNum_in2, _getQueryProcNum_in3);
        System.out.println("getQueryProcNum.result=" + _getQueryProcNum__return);


        }
        {
        System.out.println("Invoking getListJianBaoNum...");
        int _getListJianBaoNum_in0 = -534755114;
        int _getListJianBaoNum_in1 = 669225610;
        int _getListJianBaoNum__return = port.getListJianBaoNum(_getListJianBaoNum_in0, _getListJianBaoNum_in1);
        System.out.println("getListJianBaoNum.result=" + _getListJianBaoNum__return);


        }
        {
        System.out.println("Invoking getAuditDuban...");
        java.lang.String _getAuditDuban_in0 = "_getAuditDuban_in0-557149654";
        int _getAuditDuban__return = port.getAuditDuban(_getAuditDuban_in0);
        System.out.println("getAuditDuban.result=" + _getAuditDuban__return);


        }
        {
        System.out.println("Invoking batchEditItem...");
        java.lang.String _batchEditItem_in0 = "_batchEditItem_in0-845264947";
        port.batchEditItem(_batchEditItem_in0);


        }
        {
        System.out.println("Invoking getListRuQing...");
        int _getListRuQing_in0 = -1769701381;
        int _getListRuQing_in1 = -770559155;
        cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _getListRuQing__return = port.getListRuQing(_getListRuQing_in0, _getListRuQing_in1);
        System.out.println("getListRuQing.result=" + _getListRuQing__return);


        }

        System.exit(0);
    }

}
