
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.gov.laho.gzfgoa.flow.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Nov 07 16:59:04 CST 2014
 * Generated source version: 2.2.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProcInfoService",
                      portName = "ProcInfoServiceHttpPort",
                      targetNamespace = "http://webservice.flow.gzfg.kwhope.com",
                      wsdlLocation = "http://172.30.242.137:7007/fgoa/services/ProcInfoService?wsdl",
                      endpointInterface = "cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType")
                      
public class ProcInfoServicePortTypeImpl implements ProcInfoServicePortType {

    private static final Logger LOG = Logger.getLogger(ProcInfoServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#queryFlowNum(java.lang.String  in0 ,)int  in1 ,)int  in2 ,)java.lang.String  in3 ,)java.lang.String  in4 ,)java.lang.String  in5 ,)java.lang.String  in6 ,)java.lang.String  in7 ,)java.lang.String  in8 ,)java.lang.String  in9 ,)java.lang.String  in10 ,)java.lang.String  in11 ,)java.lang.String  in12 ,)java.lang.String  in13 )*
     */
    public int queryFlowNum(java.lang.String in0,int in1,int in2,java.lang.String in3,java.lang.String in4,java.lang.String in5,java.lang.String in6,java.lang.String in7,java.lang.String in8,java.lang.String in9,java.lang.String in10,java.lang.String in11,java.lang.String in12,java.lang.String in13) { 
        LOG.info("Executing operation queryFlowNum");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        System.out.println(in6);
        System.out.println(in7);
        System.out.println(in8);
        System.out.println(in9);
        System.out.println(in10);
        System.out.println(in11);
        System.out.println(in12);
        System.out.println(in13);
        try {
            int _return = -777199462;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getQueryFinishProc(java.lang.String  in0 ,)int  in1 ,)int  in2 ,)int  in3 ,)java.lang.String  in4 )*
     */
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getQueryFinishProc(java.lang.String in0,int in1,int in2,int in3,java.lang.String in4) { 
        LOG.info("Executing operation getQueryFinishProc");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        try {
            cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _return = new cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean();
            java.util.List<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean> _returnProcInfoBean = new java.util.ArrayList<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean>();
            cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean _returnProcInfoBeanVal1 = new cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean();
            _returnProcInfoBeanVal1.setActId(Integer.valueOf(753373702));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ActName = null;
            _returnProcInfoBeanVal1.setActName(_returnProcInfoBeanVal1ActName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Coding = null;
            _returnProcInfoBeanVal1.setCoding(_returnProcInfoBeanVal1Coding);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowNum = null;
            _returnProcInfoBeanVal1.setComeFlowNum(_returnProcInfoBeanVal1ComeFlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowOrg = null;
            _returnProcInfoBeanVal1.setComeFlowOrg(_returnProcInfoBeanVal1ComeFlowOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Compdatestr = null;
            _returnProcInfoBeanVal1.setCompdatestr(_returnProcInfoBeanVal1Compdatestr);
            _returnProcInfoBeanVal1.setCountnum(Integer.valueOf(1103478155));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DataLink = null;
            _returnProcInfoBeanVal1.setDataLink(_returnProcInfoBeanVal1DataLink);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DirectOrg = null;
            _returnProcInfoBeanVal1.setDirectOrg(_returnProcInfoBeanVal1DirectOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Docket = null;
            _returnProcInfoBeanVal1.setDocket(_returnProcInfoBeanVal1Docket);
            _returnProcInfoBeanVal1.setDsmId(Integer.valueOf(1493540858));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmName = null;
            _returnProcInfoBeanVal1.setDsmName(_returnProcInfoBeanVal1DsmName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmValue = null;
            _returnProcInfoBeanVal1.setDsmValue(_returnProcInfoBeanVal1DsmValue);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FileNum = null;
            _returnProcInfoBeanVal1.setFileNum(_returnProcInfoBeanVal1FileNum);
            _returnProcInfoBeanVal1.setFlag(Integer.valueOf(42451945));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowBjck = null;
            _returnProcInfoBeanVal1.setFlowBjck(_returnProcInfoBeanVal1FlowBjck);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowEndTime = null;
            _returnProcInfoBeanVal1.setFlowEndTime(_returnProcInfoBeanVal1FlowEndTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLbyj = null;
            _returnProcInfoBeanVal1.setFlowLbyj(_returnProcInfoBeanVal1FlowLbyj);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLdps = null;
            _returnProcInfoBeanVal1.setFlowLdps(_returnProcInfoBeanVal1FlowLdps);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowNum = null;
            _returnProcInfoBeanVal1.setFlowNum(_returnProcInfoBeanVal1FlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsld = null;
            _returnProcInfoBeanVal1.setFlowPsld(_returnProcInfoBeanVal1FlowPsld);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsly = null;
            _returnProcInfoBeanVal1.setFlowPsly(_returnProcInfoBeanVal1FlowPsly);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowStartTime = null;
            _returnProcInfoBeanVal1.setFlowStartTime(_returnProcInfoBeanVal1FlowStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowTitle = null;
            _returnProcInfoBeanVal1.setFlowTitle(_returnProcInfoBeanVal1FlowTitle);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Flowztc = null;
            _returnProcInfoBeanVal1.setFlowztc(_returnProcInfoBeanVal1Flowztc);
            _returnProcInfoBeanVal1.setFormId(Integer.valueOf(-1639055434));
            _returnProcInfoBeanVal1.setId(Integer.valueOf(819475141));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhOrg = null;
            _returnProcInfoBeanVal1.setJbxhOrg(_returnProcInfoBeanVal1JbxhOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhUserName = null;
            _returnProcInfoBeanVal1.setJbxhUserName(_returnProcInfoBeanVal1JbxhUserName);
            javax.xml.bind.JAXBElement<cn.gov.laho.gzfgoa.flow.webservice.ArrayOfString> _returnProcInfoBeanVal1List = null;
            _returnProcInfoBeanVal1.setList(_returnProcInfoBeanVal1List);
            _returnProcInfoBeanVal1.setNum(Integer.valueOf(1258375459));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1OrgName = null;
            _returnProcInfoBeanVal1.setOrgName(_returnProcInfoBeanVal1OrgName);
            _returnProcInfoBeanVal1.setProcId(Integer.valueOf(46353668));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ProcName = null;
            _returnProcInfoBeanVal1.setProcName(_returnProcInfoBeanVal1ProcName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Psjld = null;
            _returnProcInfoBeanVal1.setPsjld(_returnProcInfoBeanVal1Psjld);
            _returnProcInfoBeanVal1.setPsjldId(Integer.valueOf(-2022841706));
            _returnProcInfoBeanVal1.setPublicAreaId(Integer.valueOf(710122364));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceiveDataStr = null;
            _returnProcInfoBeanVal1.setReceiveDataStr(_returnProcInfoBeanVal1ReceiveDataStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStr = null;
            _returnProcInfoBeanVal1.setReceivedateStr(_returnProcInfoBeanVal1ReceivedateStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStrend = null;
            _returnProcInfoBeanVal1.setReceivedateStrend(_returnProcInfoBeanVal1ReceivedateStrend);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Reserve = null;
            _returnProcInfoBeanVal1.setReserve(_returnProcInfoBeanVal1Reserve);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1SelectYear = null;
            _returnProcInfoBeanVal1.setSelectYear(_returnProcInfoBeanVal1SelectYear);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Senddate = null;
            _returnProcInfoBeanVal1.setSenddate(_returnProcInfoBeanVal1Senddate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Sendor = null;
            _returnProcInfoBeanVal1.setSendor(_returnProcInfoBeanVal1Sendor);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1State = null;
            _returnProcInfoBeanVal1.setState(_returnProcInfoBeanVal1State);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Title = null;
            _returnProcInfoBeanVal1.setTitle(_returnProcInfoBeanVal1Title);
            _returnProcInfoBeanVal1.setTypeId(Integer.valueOf(1113425213));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Unit = null;
            _returnProcInfoBeanVal1.setUnit(_returnProcInfoBeanVal1Unit);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UrgencyFlag = null;
            _returnProcInfoBeanVal1.setUrgencyFlag(_returnProcInfoBeanVal1UrgencyFlag);
            _returnProcInfoBeanVal1.setUserId(Integer.valueOf(721243490));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UserName = null;
            _returnProcInfoBeanVal1.setUserName(_returnProcInfoBeanVal1UserName);
            _returnProcInfoBeanVal1.setWorkItemId(Integer.valueOf(784914003));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1XbOrg = null;
            _returnProcInfoBeanVal1.setXbOrg(_returnProcInfoBeanVal1XbOrg);
            _returnProcInfoBean.add(_returnProcInfoBeanVal1);
            _return.getProcInfoBean().addAll(_returnProcInfoBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getQueryFinishProcNum(java.lang.String  in0 ,)int  in1 ,)int  in2 ,)int  in3 ,)java.lang.String  in4 )*
     */
    public int getQueryFinishProcNum(java.lang.String in0,int in1,int in2,int in3,java.lang.String in4) { 
        LOG.info("Executing operation getQueryFinishProcNum");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        try {
            int _return = 2010712142;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getListRuQingNum(int  in0 ,)int  in1 )*
     */
    public int getListRuQingNum(int in0,int in1) { 
        LOG.info("Executing operation getListRuQingNum");
        System.out.println(in0);
        System.out.println(in1);
        try {
            int _return = -1283890997;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getListJianBao(int  in0 ,)int  in1 )*
     */
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getListJianBao(int in0,int in1) { 
        LOG.info("Executing operation getListJianBao");
        System.out.println(in0);
        System.out.println(in1);
        try {
            cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _return = new cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean();
            java.util.List<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean> _returnProcInfoBean = new java.util.ArrayList<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean>();
            cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean _returnProcInfoBeanVal1 = new cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean();
            _returnProcInfoBeanVal1.setActId(Integer.valueOf(-1523626408));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ActName = null;
            _returnProcInfoBeanVal1.setActName(_returnProcInfoBeanVal1ActName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Coding = null;
            _returnProcInfoBeanVal1.setCoding(_returnProcInfoBeanVal1Coding);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowNum = null;
            _returnProcInfoBeanVal1.setComeFlowNum(_returnProcInfoBeanVal1ComeFlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowOrg = null;
            _returnProcInfoBeanVal1.setComeFlowOrg(_returnProcInfoBeanVal1ComeFlowOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Compdatestr = null;
            _returnProcInfoBeanVal1.setCompdatestr(_returnProcInfoBeanVal1Compdatestr);
            _returnProcInfoBeanVal1.setCountnum(Integer.valueOf(60131148));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DataLink = null;
            _returnProcInfoBeanVal1.setDataLink(_returnProcInfoBeanVal1DataLink);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DirectOrg = null;
            _returnProcInfoBeanVal1.setDirectOrg(_returnProcInfoBeanVal1DirectOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Docket = null;
            _returnProcInfoBeanVal1.setDocket(_returnProcInfoBeanVal1Docket);
            _returnProcInfoBeanVal1.setDsmId(Integer.valueOf(1523488796));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmName = null;
            _returnProcInfoBeanVal1.setDsmName(_returnProcInfoBeanVal1DsmName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmValue = null;
            _returnProcInfoBeanVal1.setDsmValue(_returnProcInfoBeanVal1DsmValue);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FileNum = null;
            _returnProcInfoBeanVal1.setFileNum(_returnProcInfoBeanVal1FileNum);
            _returnProcInfoBeanVal1.setFlag(Integer.valueOf(-667497285));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowBjck = null;
            _returnProcInfoBeanVal1.setFlowBjck(_returnProcInfoBeanVal1FlowBjck);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowEndTime = null;
            _returnProcInfoBeanVal1.setFlowEndTime(_returnProcInfoBeanVal1FlowEndTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLbyj = null;
            _returnProcInfoBeanVal1.setFlowLbyj(_returnProcInfoBeanVal1FlowLbyj);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLdps = null;
            _returnProcInfoBeanVal1.setFlowLdps(_returnProcInfoBeanVal1FlowLdps);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowNum = null;
            _returnProcInfoBeanVal1.setFlowNum(_returnProcInfoBeanVal1FlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsld = null;
            _returnProcInfoBeanVal1.setFlowPsld(_returnProcInfoBeanVal1FlowPsld);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsly = null;
            _returnProcInfoBeanVal1.setFlowPsly(_returnProcInfoBeanVal1FlowPsly);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowStartTime = null;
            _returnProcInfoBeanVal1.setFlowStartTime(_returnProcInfoBeanVal1FlowStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowTitle = null;
            _returnProcInfoBeanVal1.setFlowTitle(_returnProcInfoBeanVal1FlowTitle);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Flowztc = null;
            _returnProcInfoBeanVal1.setFlowztc(_returnProcInfoBeanVal1Flowztc);
            _returnProcInfoBeanVal1.setFormId(Integer.valueOf(-1100207701));
            _returnProcInfoBeanVal1.setId(Integer.valueOf(-1023499878));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhOrg = null;
            _returnProcInfoBeanVal1.setJbxhOrg(_returnProcInfoBeanVal1JbxhOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhUserName = null;
            _returnProcInfoBeanVal1.setJbxhUserName(_returnProcInfoBeanVal1JbxhUserName);
            javax.xml.bind.JAXBElement<cn.gov.laho.gzfgoa.flow.webservice.ArrayOfString> _returnProcInfoBeanVal1List = null;
            _returnProcInfoBeanVal1.setList(_returnProcInfoBeanVal1List);
            _returnProcInfoBeanVal1.setNum(Integer.valueOf(1117312181));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1OrgName = null;
            _returnProcInfoBeanVal1.setOrgName(_returnProcInfoBeanVal1OrgName);
            _returnProcInfoBeanVal1.setProcId(Integer.valueOf(-576663793));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ProcName = null;
            _returnProcInfoBeanVal1.setProcName(_returnProcInfoBeanVal1ProcName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Psjld = null;
            _returnProcInfoBeanVal1.setPsjld(_returnProcInfoBeanVal1Psjld);
            _returnProcInfoBeanVal1.setPsjldId(Integer.valueOf(-1249503385));
            _returnProcInfoBeanVal1.setPublicAreaId(Integer.valueOf(1018375248));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceiveDataStr = null;
            _returnProcInfoBeanVal1.setReceiveDataStr(_returnProcInfoBeanVal1ReceiveDataStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStr = null;
            _returnProcInfoBeanVal1.setReceivedateStr(_returnProcInfoBeanVal1ReceivedateStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStrend = null;
            _returnProcInfoBeanVal1.setReceivedateStrend(_returnProcInfoBeanVal1ReceivedateStrend);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Reserve = null;
            _returnProcInfoBeanVal1.setReserve(_returnProcInfoBeanVal1Reserve);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1SelectYear = null;
            _returnProcInfoBeanVal1.setSelectYear(_returnProcInfoBeanVal1SelectYear);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Senddate = null;
            _returnProcInfoBeanVal1.setSenddate(_returnProcInfoBeanVal1Senddate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Sendor = null;
            _returnProcInfoBeanVal1.setSendor(_returnProcInfoBeanVal1Sendor);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1State = null;
            _returnProcInfoBeanVal1.setState(_returnProcInfoBeanVal1State);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Title = null;
            _returnProcInfoBeanVal1.setTitle(_returnProcInfoBeanVal1Title);
            _returnProcInfoBeanVal1.setTypeId(Integer.valueOf(1254139604));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Unit = null;
            _returnProcInfoBeanVal1.setUnit(_returnProcInfoBeanVal1Unit);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UrgencyFlag = null;
            _returnProcInfoBeanVal1.setUrgencyFlag(_returnProcInfoBeanVal1UrgencyFlag);
            _returnProcInfoBeanVal1.setUserId(Integer.valueOf(808556991));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UserName = null;
            _returnProcInfoBeanVal1.setUserName(_returnProcInfoBeanVal1UserName);
            _returnProcInfoBeanVal1.setWorkItemId(Integer.valueOf(-5815058));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1XbOrg = null;
            _returnProcInfoBeanVal1.setXbOrg(_returnProcInfoBeanVal1XbOrg);
            _returnProcInfoBean.add(_returnProcInfoBeanVal1);
            _return.getProcInfoBean().addAll(_returnProcInfoBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getWeiWanDuban(java.lang.String  in0 ,)java.lang.String  in1 )*
     */
    public int getWeiWanDuban(java.lang.String in0,java.lang.String in1) { 
        LOG.info("Executing operation getWeiWanDuban");
        System.out.println(in0);
        System.out.println(in1);
        try {
            int _return = 1040897283;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getListProc(java.lang.String  in0 ,)int  in1 ,)int  in2 ,)int  in3 ,)java.lang.String  in4 ,)java.lang.String  in5 )*
     */
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getListProc(java.lang.String in0,int in1,int in2,int in3,java.lang.String in4,java.lang.String in5) { 
        LOG.info("Executing operation getListProc");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        try {
            cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _return = new cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean();
            java.util.List<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean> _returnProcInfoBean = new java.util.ArrayList<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean>();
            cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean _returnProcInfoBeanVal1 = new cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean();
            _returnProcInfoBeanVal1.setActId(Integer.valueOf(183506252));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ActName = null;
            _returnProcInfoBeanVal1.setActName(_returnProcInfoBeanVal1ActName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Coding = null;
            _returnProcInfoBeanVal1.setCoding(_returnProcInfoBeanVal1Coding);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowNum = null;
            _returnProcInfoBeanVal1.setComeFlowNum(_returnProcInfoBeanVal1ComeFlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowOrg = null;
            _returnProcInfoBeanVal1.setComeFlowOrg(_returnProcInfoBeanVal1ComeFlowOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Compdatestr = null;
            _returnProcInfoBeanVal1.setCompdatestr(_returnProcInfoBeanVal1Compdatestr);
            _returnProcInfoBeanVal1.setCountnum(Integer.valueOf(2049485789));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DataLink = null;
            _returnProcInfoBeanVal1.setDataLink(_returnProcInfoBeanVal1DataLink);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DirectOrg = null;
            _returnProcInfoBeanVal1.setDirectOrg(_returnProcInfoBeanVal1DirectOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Docket = null;
            _returnProcInfoBeanVal1.setDocket(_returnProcInfoBeanVal1Docket);
            _returnProcInfoBeanVal1.setDsmId(Integer.valueOf(-1175172781));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmName = null;
            _returnProcInfoBeanVal1.setDsmName(_returnProcInfoBeanVal1DsmName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmValue = null;
            _returnProcInfoBeanVal1.setDsmValue(_returnProcInfoBeanVal1DsmValue);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FileNum = null;
            _returnProcInfoBeanVal1.setFileNum(_returnProcInfoBeanVal1FileNum);
            _returnProcInfoBeanVal1.setFlag(Integer.valueOf(-31133812));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowBjck = null;
            _returnProcInfoBeanVal1.setFlowBjck(_returnProcInfoBeanVal1FlowBjck);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowEndTime = null;
            _returnProcInfoBeanVal1.setFlowEndTime(_returnProcInfoBeanVal1FlowEndTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLbyj = null;
            _returnProcInfoBeanVal1.setFlowLbyj(_returnProcInfoBeanVal1FlowLbyj);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLdps = null;
            _returnProcInfoBeanVal1.setFlowLdps(_returnProcInfoBeanVal1FlowLdps);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowNum = null;
            _returnProcInfoBeanVal1.setFlowNum(_returnProcInfoBeanVal1FlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsld = null;
            _returnProcInfoBeanVal1.setFlowPsld(_returnProcInfoBeanVal1FlowPsld);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsly = null;
            _returnProcInfoBeanVal1.setFlowPsly(_returnProcInfoBeanVal1FlowPsly);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowStartTime = null;
            _returnProcInfoBeanVal1.setFlowStartTime(_returnProcInfoBeanVal1FlowStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowTitle = null;
            _returnProcInfoBeanVal1.setFlowTitle(_returnProcInfoBeanVal1FlowTitle);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Flowztc = null;
            _returnProcInfoBeanVal1.setFlowztc(_returnProcInfoBeanVal1Flowztc);
            _returnProcInfoBeanVal1.setFormId(Integer.valueOf(983516033));
            _returnProcInfoBeanVal1.setId(Integer.valueOf(-339779334));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhOrg = null;
            _returnProcInfoBeanVal1.setJbxhOrg(_returnProcInfoBeanVal1JbxhOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhUserName = null;
            _returnProcInfoBeanVal1.setJbxhUserName(_returnProcInfoBeanVal1JbxhUserName);
            javax.xml.bind.JAXBElement<cn.gov.laho.gzfgoa.flow.webservice.ArrayOfString> _returnProcInfoBeanVal1List = null;
            _returnProcInfoBeanVal1.setList(_returnProcInfoBeanVal1List);
            _returnProcInfoBeanVal1.setNum(Integer.valueOf(-1997468952));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1OrgName = null;
            _returnProcInfoBeanVal1.setOrgName(_returnProcInfoBeanVal1OrgName);
            _returnProcInfoBeanVal1.setProcId(Integer.valueOf(-560910836));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ProcName = null;
            _returnProcInfoBeanVal1.setProcName(_returnProcInfoBeanVal1ProcName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Psjld = null;
            _returnProcInfoBeanVal1.setPsjld(_returnProcInfoBeanVal1Psjld);
            _returnProcInfoBeanVal1.setPsjldId(Integer.valueOf(1777230618));
            _returnProcInfoBeanVal1.setPublicAreaId(Integer.valueOf(-1458793784));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceiveDataStr = null;
            _returnProcInfoBeanVal1.setReceiveDataStr(_returnProcInfoBeanVal1ReceiveDataStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStr = null;
            _returnProcInfoBeanVal1.setReceivedateStr(_returnProcInfoBeanVal1ReceivedateStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStrend = null;
            _returnProcInfoBeanVal1.setReceivedateStrend(_returnProcInfoBeanVal1ReceivedateStrend);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Reserve = null;
            _returnProcInfoBeanVal1.setReserve(_returnProcInfoBeanVal1Reserve);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1SelectYear = null;
            _returnProcInfoBeanVal1.setSelectYear(_returnProcInfoBeanVal1SelectYear);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Senddate = null;
            _returnProcInfoBeanVal1.setSenddate(_returnProcInfoBeanVal1Senddate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Sendor = null;
            _returnProcInfoBeanVal1.setSendor(_returnProcInfoBeanVal1Sendor);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1State = null;
            _returnProcInfoBeanVal1.setState(_returnProcInfoBeanVal1State);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Title = null;
            _returnProcInfoBeanVal1.setTitle(_returnProcInfoBeanVal1Title);
            _returnProcInfoBeanVal1.setTypeId(Integer.valueOf(550890005));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Unit = null;
            _returnProcInfoBeanVal1.setUnit(_returnProcInfoBeanVal1Unit);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UrgencyFlag = null;
            _returnProcInfoBeanVal1.setUrgencyFlag(_returnProcInfoBeanVal1UrgencyFlag);
            _returnProcInfoBeanVal1.setUserId(Integer.valueOf(1333613872));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UserName = null;
            _returnProcInfoBeanVal1.setUserName(_returnProcInfoBeanVal1UserName);
            _returnProcInfoBeanVal1.setWorkItemId(Integer.valueOf(1606454516));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1XbOrg = null;
            _returnProcInfoBeanVal1.setXbOrg(_returnProcInfoBeanVal1XbOrg);
            _returnProcInfoBean.add(_returnProcInfoBeanVal1);
            _return.getProcInfoBean().addAll(_returnProcInfoBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getListProcNum(java.lang.String  in0 ,)int  in1 ,)int  in2 ,)int  in3 ,)java.lang.String  in4 ,)java.lang.String  in5 )*
     */
    public int getListProcNum(java.lang.String in0,int in1,int in2,int in3,java.lang.String in4,java.lang.String in5) { 
        LOG.info("Executing operation getListProcNum");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        try {
            int _return = -1823592192;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#queryFlow(java.lang.String  in0 ,)int  in1 ,)int  in2 ,)java.lang.String  in3 ,)java.lang.String  in4 ,)java.lang.String  in5 ,)java.lang.String  in6 ,)java.lang.String  in7 ,)java.lang.String  in8 ,)java.lang.String  in9 ,)java.lang.String  in10 ,)java.lang.String  in11 ,)java.lang.String  in12 ,)java.lang.String  in13 ,)int  in14 ,)int  in15 )*
     */
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean queryFlow(java.lang.String in0,int in1,int in2,java.lang.String in3,java.lang.String in4,java.lang.String in5,java.lang.String in6,java.lang.String in7,java.lang.String in8,java.lang.String in9,java.lang.String in10,java.lang.String in11,java.lang.String in12,java.lang.String in13,int in14,int in15) { 
        LOG.info("Executing operation queryFlow");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        System.out.println(in6);
        System.out.println(in7);
        System.out.println(in8);
        System.out.println(in9);
        System.out.println(in10);
        System.out.println(in11);
        System.out.println(in12);
        System.out.println(in13);
        System.out.println(in14);
        System.out.println(in15);
        try {
            cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _return = new cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean();
            java.util.List<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean> _returnProcInfoBean = new java.util.ArrayList<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean>();
            cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean _returnProcInfoBeanVal1 = new cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean();
            _returnProcInfoBeanVal1.setActId(Integer.valueOf(-695450261));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ActName = null;
            _returnProcInfoBeanVal1.setActName(_returnProcInfoBeanVal1ActName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Coding = null;
            _returnProcInfoBeanVal1.setCoding(_returnProcInfoBeanVal1Coding);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowNum = null;
            _returnProcInfoBeanVal1.setComeFlowNum(_returnProcInfoBeanVal1ComeFlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowOrg = null;
            _returnProcInfoBeanVal1.setComeFlowOrg(_returnProcInfoBeanVal1ComeFlowOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Compdatestr = null;
            _returnProcInfoBeanVal1.setCompdatestr(_returnProcInfoBeanVal1Compdatestr);
            _returnProcInfoBeanVal1.setCountnum(Integer.valueOf(-2074906443));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DataLink = null;
            _returnProcInfoBeanVal1.setDataLink(_returnProcInfoBeanVal1DataLink);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DirectOrg = null;
            _returnProcInfoBeanVal1.setDirectOrg(_returnProcInfoBeanVal1DirectOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Docket = null;
            _returnProcInfoBeanVal1.setDocket(_returnProcInfoBeanVal1Docket);
            _returnProcInfoBeanVal1.setDsmId(Integer.valueOf(100054361));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmName = null;
            _returnProcInfoBeanVal1.setDsmName(_returnProcInfoBeanVal1DsmName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmValue = null;
            _returnProcInfoBeanVal1.setDsmValue(_returnProcInfoBeanVal1DsmValue);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FileNum = null;
            _returnProcInfoBeanVal1.setFileNum(_returnProcInfoBeanVal1FileNum);
            _returnProcInfoBeanVal1.setFlag(Integer.valueOf(223998853));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowBjck = null;
            _returnProcInfoBeanVal1.setFlowBjck(_returnProcInfoBeanVal1FlowBjck);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowEndTime = null;
            _returnProcInfoBeanVal1.setFlowEndTime(_returnProcInfoBeanVal1FlowEndTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLbyj = null;
            _returnProcInfoBeanVal1.setFlowLbyj(_returnProcInfoBeanVal1FlowLbyj);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLdps = null;
            _returnProcInfoBeanVal1.setFlowLdps(_returnProcInfoBeanVal1FlowLdps);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowNum = null;
            _returnProcInfoBeanVal1.setFlowNum(_returnProcInfoBeanVal1FlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsld = null;
            _returnProcInfoBeanVal1.setFlowPsld(_returnProcInfoBeanVal1FlowPsld);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsly = null;
            _returnProcInfoBeanVal1.setFlowPsly(_returnProcInfoBeanVal1FlowPsly);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowStartTime = null;
            _returnProcInfoBeanVal1.setFlowStartTime(_returnProcInfoBeanVal1FlowStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowTitle = null;
            _returnProcInfoBeanVal1.setFlowTitle(_returnProcInfoBeanVal1FlowTitle);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Flowztc = null;
            _returnProcInfoBeanVal1.setFlowztc(_returnProcInfoBeanVal1Flowztc);
            _returnProcInfoBeanVal1.setFormId(Integer.valueOf(-186209544));
            _returnProcInfoBeanVal1.setId(Integer.valueOf(-1972876242));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhOrg = null;
            _returnProcInfoBeanVal1.setJbxhOrg(_returnProcInfoBeanVal1JbxhOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhUserName = null;
            _returnProcInfoBeanVal1.setJbxhUserName(_returnProcInfoBeanVal1JbxhUserName);
            javax.xml.bind.JAXBElement<cn.gov.laho.gzfgoa.flow.webservice.ArrayOfString> _returnProcInfoBeanVal1List = null;
            _returnProcInfoBeanVal1.setList(_returnProcInfoBeanVal1List);
            _returnProcInfoBeanVal1.setNum(Integer.valueOf(518598513));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1OrgName = null;
            _returnProcInfoBeanVal1.setOrgName(_returnProcInfoBeanVal1OrgName);
            _returnProcInfoBeanVal1.setProcId(Integer.valueOf(862227145));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ProcName = null;
            _returnProcInfoBeanVal1.setProcName(_returnProcInfoBeanVal1ProcName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Psjld = null;
            _returnProcInfoBeanVal1.setPsjld(_returnProcInfoBeanVal1Psjld);
            _returnProcInfoBeanVal1.setPsjldId(Integer.valueOf(-971355428));
            _returnProcInfoBeanVal1.setPublicAreaId(Integer.valueOf(1729246213));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceiveDataStr = null;
            _returnProcInfoBeanVal1.setReceiveDataStr(_returnProcInfoBeanVal1ReceiveDataStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStr = null;
            _returnProcInfoBeanVal1.setReceivedateStr(_returnProcInfoBeanVal1ReceivedateStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStrend = null;
            _returnProcInfoBeanVal1.setReceivedateStrend(_returnProcInfoBeanVal1ReceivedateStrend);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Reserve = null;
            _returnProcInfoBeanVal1.setReserve(_returnProcInfoBeanVal1Reserve);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1SelectYear = null;
            _returnProcInfoBeanVal1.setSelectYear(_returnProcInfoBeanVal1SelectYear);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Senddate = null;
            _returnProcInfoBeanVal1.setSenddate(_returnProcInfoBeanVal1Senddate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Sendor = null;
            _returnProcInfoBeanVal1.setSendor(_returnProcInfoBeanVal1Sendor);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1State = null;
            _returnProcInfoBeanVal1.setState(_returnProcInfoBeanVal1State);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Title = null;
            _returnProcInfoBeanVal1.setTitle(_returnProcInfoBeanVal1Title);
            _returnProcInfoBeanVal1.setTypeId(Integer.valueOf(-298748936));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Unit = null;
            _returnProcInfoBeanVal1.setUnit(_returnProcInfoBeanVal1Unit);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UrgencyFlag = null;
            _returnProcInfoBeanVal1.setUrgencyFlag(_returnProcInfoBeanVal1UrgencyFlag);
            _returnProcInfoBeanVal1.setUserId(Integer.valueOf(1197535855));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UserName = null;
            _returnProcInfoBeanVal1.setUserName(_returnProcInfoBeanVal1UserName);
            _returnProcInfoBeanVal1.setWorkItemId(Integer.valueOf(-1010532580));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1XbOrg = null;
            _returnProcInfoBeanVal1.setXbOrg(_returnProcInfoBeanVal1XbOrg);
            _returnProcInfoBean.add(_returnProcInfoBeanVal1);
            _return.getProcInfoBean().addAll(_returnProcInfoBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getListProcInfo(int  in0 ,)java.lang.String  in1 )*
     */
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getListProcInfo(int in0,java.lang.String in1) { 
        LOG.info("Executing operation getListProcInfo");
        System.out.println(in0);
        System.out.println(in1);
        try {
            cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _return = new cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean();
            java.util.List<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean> _returnProcInfoBean = new java.util.ArrayList<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean>();
            cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean _returnProcInfoBeanVal1 = new cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean();
            _returnProcInfoBeanVal1.setActId(Integer.valueOf(-1854127425));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ActName = null;
            _returnProcInfoBeanVal1.setActName(_returnProcInfoBeanVal1ActName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Coding = null;
            _returnProcInfoBeanVal1.setCoding(_returnProcInfoBeanVal1Coding);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowNum = null;
            _returnProcInfoBeanVal1.setComeFlowNum(_returnProcInfoBeanVal1ComeFlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowOrg = null;
            _returnProcInfoBeanVal1.setComeFlowOrg(_returnProcInfoBeanVal1ComeFlowOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Compdatestr = null;
            _returnProcInfoBeanVal1.setCompdatestr(_returnProcInfoBeanVal1Compdatestr);
            _returnProcInfoBeanVal1.setCountnum(Integer.valueOf(566042417));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DataLink = null;
            _returnProcInfoBeanVal1.setDataLink(_returnProcInfoBeanVal1DataLink);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DirectOrg = null;
            _returnProcInfoBeanVal1.setDirectOrg(_returnProcInfoBeanVal1DirectOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Docket = null;
            _returnProcInfoBeanVal1.setDocket(_returnProcInfoBeanVal1Docket);
            _returnProcInfoBeanVal1.setDsmId(Integer.valueOf(-1288713678));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmName = null;
            _returnProcInfoBeanVal1.setDsmName(_returnProcInfoBeanVal1DsmName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmValue = null;
            _returnProcInfoBeanVal1.setDsmValue(_returnProcInfoBeanVal1DsmValue);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FileNum = null;
            _returnProcInfoBeanVal1.setFileNum(_returnProcInfoBeanVal1FileNum);
            _returnProcInfoBeanVal1.setFlag(Integer.valueOf(-1189053259));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowBjck = null;
            _returnProcInfoBeanVal1.setFlowBjck(_returnProcInfoBeanVal1FlowBjck);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowEndTime = null;
            _returnProcInfoBeanVal1.setFlowEndTime(_returnProcInfoBeanVal1FlowEndTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLbyj = null;
            _returnProcInfoBeanVal1.setFlowLbyj(_returnProcInfoBeanVal1FlowLbyj);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLdps = null;
            _returnProcInfoBeanVal1.setFlowLdps(_returnProcInfoBeanVal1FlowLdps);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowNum = null;
            _returnProcInfoBeanVal1.setFlowNum(_returnProcInfoBeanVal1FlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsld = null;
            _returnProcInfoBeanVal1.setFlowPsld(_returnProcInfoBeanVal1FlowPsld);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsly = null;
            _returnProcInfoBeanVal1.setFlowPsly(_returnProcInfoBeanVal1FlowPsly);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowStartTime = null;
            _returnProcInfoBeanVal1.setFlowStartTime(_returnProcInfoBeanVal1FlowStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowTitle = null;
            _returnProcInfoBeanVal1.setFlowTitle(_returnProcInfoBeanVal1FlowTitle);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Flowztc = null;
            _returnProcInfoBeanVal1.setFlowztc(_returnProcInfoBeanVal1Flowztc);
            _returnProcInfoBeanVal1.setFormId(Integer.valueOf(1460321923));
            _returnProcInfoBeanVal1.setId(Integer.valueOf(1782471193));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhOrg = null;
            _returnProcInfoBeanVal1.setJbxhOrg(_returnProcInfoBeanVal1JbxhOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhUserName = null;
            _returnProcInfoBeanVal1.setJbxhUserName(_returnProcInfoBeanVal1JbxhUserName);
            javax.xml.bind.JAXBElement<cn.gov.laho.gzfgoa.flow.webservice.ArrayOfString> _returnProcInfoBeanVal1List = null;
            _returnProcInfoBeanVal1.setList(_returnProcInfoBeanVal1List);
            _returnProcInfoBeanVal1.setNum(Integer.valueOf(49338628));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1OrgName = null;
            _returnProcInfoBeanVal1.setOrgName(_returnProcInfoBeanVal1OrgName);
            _returnProcInfoBeanVal1.setProcId(Integer.valueOf(-1329692172));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ProcName = null;
            _returnProcInfoBeanVal1.setProcName(_returnProcInfoBeanVal1ProcName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Psjld = null;
            _returnProcInfoBeanVal1.setPsjld(_returnProcInfoBeanVal1Psjld);
            _returnProcInfoBeanVal1.setPsjldId(Integer.valueOf(862538460));
            _returnProcInfoBeanVal1.setPublicAreaId(Integer.valueOf(-1835195680));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceiveDataStr = null;
            _returnProcInfoBeanVal1.setReceiveDataStr(_returnProcInfoBeanVal1ReceiveDataStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStr = null;
            _returnProcInfoBeanVal1.setReceivedateStr(_returnProcInfoBeanVal1ReceivedateStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStrend = null;
            _returnProcInfoBeanVal1.setReceivedateStrend(_returnProcInfoBeanVal1ReceivedateStrend);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Reserve = null;
            _returnProcInfoBeanVal1.setReserve(_returnProcInfoBeanVal1Reserve);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1SelectYear = null;
            _returnProcInfoBeanVal1.setSelectYear(_returnProcInfoBeanVal1SelectYear);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Senddate = null;
            _returnProcInfoBeanVal1.setSenddate(_returnProcInfoBeanVal1Senddate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Sendor = null;
            _returnProcInfoBeanVal1.setSendor(_returnProcInfoBeanVal1Sendor);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1State = null;
            _returnProcInfoBeanVal1.setState(_returnProcInfoBeanVal1State);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Title = null;
            _returnProcInfoBeanVal1.setTitle(_returnProcInfoBeanVal1Title);
            _returnProcInfoBeanVal1.setTypeId(Integer.valueOf(172433018));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Unit = null;
            _returnProcInfoBeanVal1.setUnit(_returnProcInfoBeanVal1Unit);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UrgencyFlag = null;
            _returnProcInfoBeanVal1.setUrgencyFlag(_returnProcInfoBeanVal1UrgencyFlag);
            _returnProcInfoBeanVal1.setUserId(Integer.valueOf(-1169222140));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UserName = null;
            _returnProcInfoBeanVal1.setUserName(_returnProcInfoBeanVal1UserName);
            _returnProcInfoBeanVal1.setWorkItemId(Integer.valueOf(-1750863171));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1XbOrg = null;
            _returnProcInfoBeanVal1.setXbOrg(_returnProcInfoBeanVal1XbOrg);
            _returnProcInfoBean.add(_returnProcInfoBeanVal1);
            _return.getProcInfoBean().addAll(_returnProcInfoBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getQueryProc(java.lang.String  in0 ,)int  in1 ,)int  in2 ,)int  in3 )*
     */
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getQueryProc(java.lang.String in0,int in1,int in2,int in3) { 
        LOG.info("Executing operation getQueryProc");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        try {
            cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _return = new cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean();
            java.util.List<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean> _returnProcInfoBean = new java.util.ArrayList<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean>();
            cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean _returnProcInfoBeanVal1 = new cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean();
            _returnProcInfoBeanVal1.setActId(Integer.valueOf(2018519188));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ActName = null;
            _returnProcInfoBeanVal1.setActName(_returnProcInfoBeanVal1ActName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Coding = null;
            _returnProcInfoBeanVal1.setCoding(_returnProcInfoBeanVal1Coding);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowNum = null;
            _returnProcInfoBeanVal1.setComeFlowNum(_returnProcInfoBeanVal1ComeFlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowOrg = null;
            _returnProcInfoBeanVal1.setComeFlowOrg(_returnProcInfoBeanVal1ComeFlowOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Compdatestr = null;
            _returnProcInfoBeanVal1.setCompdatestr(_returnProcInfoBeanVal1Compdatestr);
            _returnProcInfoBeanVal1.setCountnum(Integer.valueOf(427955814));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DataLink = null;
            _returnProcInfoBeanVal1.setDataLink(_returnProcInfoBeanVal1DataLink);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DirectOrg = null;
            _returnProcInfoBeanVal1.setDirectOrg(_returnProcInfoBeanVal1DirectOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Docket = null;
            _returnProcInfoBeanVal1.setDocket(_returnProcInfoBeanVal1Docket);
            _returnProcInfoBeanVal1.setDsmId(Integer.valueOf(858402248));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmName = null;
            _returnProcInfoBeanVal1.setDsmName(_returnProcInfoBeanVal1DsmName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmValue = null;
            _returnProcInfoBeanVal1.setDsmValue(_returnProcInfoBeanVal1DsmValue);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FileNum = null;
            _returnProcInfoBeanVal1.setFileNum(_returnProcInfoBeanVal1FileNum);
            _returnProcInfoBeanVal1.setFlag(Integer.valueOf(37244613));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowBjck = null;
            _returnProcInfoBeanVal1.setFlowBjck(_returnProcInfoBeanVal1FlowBjck);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowEndTime = null;
            _returnProcInfoBeanVal1.setFlowEndTime(_returnProcInfoBeanVal1FlowEndTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLbyj = null;
            _returnProcInfoBeanVal1.setFlowLbyj(_returnProcInfoBeanVal1FlowLbyj);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLdps = null;
            _returnProcInfoBeanVal1.setFlowLdps(_returnProcInfoBeanVal1FlowLdps);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowNum = null;
            _returnProcInfoBeanVal1.setFlowNum(_returnProcInfoBeanVal1FlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsld = null;
            _returnProcInfoBeanVal1.setFlowPsld(_returnProcInfoBeanVal1FlowPsld);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsly = null;
            _returnProcInfoBeanVal1.setFlowPsly(_returnProcInfoBeanVal1FlowPsly);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowStartTime = null;
            _returnProcInfoBeanVal1.setFlowStartTime(_returnProcInfoBeanVal1FlowStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowTitle = null;
            _returnProcInfoBeanVal1.setFlowTitle(_returnProcInfoBeanVal1FlowTitle);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Flowztc = null;
            _returnProcInfoBeanVal1.setFlowztc(_returnProcInfoBeanVal1Flowztc);
            _returnProcInfoBeanVal1.setFormId(Integer.valueOf(-239391201));
            _returnProcInfoBeanVal1.setId(Integer.valueOf(-1314581819));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhOrg = null;
            _returnProcInfoBeanVal1.setJbxhOrg(_returnProcInfoBeanVal1JbxhOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhUserName = null;
            _returnProcInfoBeanVal1.setJbxhUserName(_returnProcInfoBeanVal1JbxhUserName);
            javax.xml.bind.JAXBElement<cn.gov.laho.gzfgoa.flow.webservice.ArrayOfString> _returnProcInfoBeanVal1List = null;
            _returnProcInfoBeanVal1.setList(_returnProcInfoBeanVal1List);
            _returnProcInfoBeanVal1.setNum(Integer.valueOf(-1637660181));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1OrgName = null;
            _returnProcInfoBeanVal1.setOrgName(_returnProcInfoBeanVal1OrgName);
            _returnProcInfoBeanVal1.setProcId(Integer.valueOf(622611396));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ProcName = null;
            _returnProcInfoBeanVal1.setProcName(_returnProcInfoBeanVal1ProcName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Psjld = null;
            _returnProcInfoBeanVal1.setPsjld(_returnProcInfoBeanVal1Psjld);
            _returnProcInfoBeanVal1.setPsjldId(Integer.valueOf(-1893980045));
            _returnProcInfoBeanVal1.setPublicAreaId(Integer.valueOf(-1569730597));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceiveDataStr = null;
            _returnProcInfoBeanVal1.setReceiveDataStr(_returnProcInfoBeanVal1ReceiveDataStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStr = null;
            _returnProcInfoBeanVal1.setReceivedateStr(_returnProcInfoBeanVal1ReceivedateStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStrend = null;
            _returnProcInfoBeanVal1.setReceivedateStrend(_returnProcInfoBeanVal1ReceivedateStrend);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Reserve = null;
            _returnProcInfoBeanVal1.setReserve(_returnProcInfoBeanVal1Reserve);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1SelectYear = null;
            _returnProcInfoBeanVal1.setSelectYear(_returnProcInfoBeanVal1SelectYear);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Senddate = null;
            _returnProcInfoBeanVal1.setSenddate(_returnProcInfoBeanVal1Senddate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Sendor = null;
            _returnProcInfoBeanVal1.setSendor(_returnProcInfoBeanVal1Sendor);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1State = null;
            _returnProcInfoBeanVal1.setState(_returnProcInfoBeanVal1State);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Title = null;
            _returnProcInfoBeanVal1.setTitle(_returnProcInfoBeanVal1Title);
            _returnProcInfoBeanVal1.setTypeId(Integer.valueOf(-323427788));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Unit = null;
            _returnProcInfoBeanVal1.setUnit(_returnProcInfoBeanVal1Unit);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UrgencyFlag = null;
            _returnProcInfoBeanVal1.setUrgencyFlag(_returnProcInfoBeanVal1UrgencyFlag);
            _returnProcInfoBeanVal1.setUserId(Integer.valueOf(1787581822));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UserName = null;
            _returnProcInfoBeanVal1.setUserName(_returnProcInfoBeanVal1UserName);
            _returnProcInfoBeanVal1.setWorkItemId(Integer.valueOf(-982545405));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1XbOrg = null;
            _returnProcInfoBeanVal1.setXbOrg(_returnProcInfoBeanVal1XbOrg);
            _returnProcInfoBean.add(_returnProcInfoBeanVal1);
            _return.getProcInfoBean().addAll(_returnProcInfoBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getQueryProcNum(java.lang.String  in0 ,)int  in1 ,)int  in2 ,)int  in3 )*
     */
    public int getQueryProcNum(java.lang.String in0,int in1,int in2,int in3) { 
        LOG.info("Executing operation getQueryProcNum");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        try {
            int _return = 1780065948;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getListJianBaoNum(int  in0 ,)int  in1 )*
     */
    public int getListJianBaoNum(int in0,int in1) { 
        LOG.info("Executing operation getListJianBaoNum");
        System.out.println(in0);
        System.out.println(in1);
        try {
            int _return = -1698778594;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getAuditDuban(java.lang.String  in0 )*
     */
    public int getAuditDuban(java.lang.String in0) { 
        LOG.info("Executing operation getAuditDuban");
        System.out.println(in0);
        try {
            int _return = -1102386770;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#batchEditItem(java.lang.String  in0 )*
     */
    public void batchEditItem(java.lang.String in0) { 
        LOG.info("Executing operation batchEditItem");
        System.out.println(in0);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.gov.laho.gzfgoa.flow.webservice.ProcInfoServicePortType#getListRuQing(int  in0 ,)int  in1 )*
     */
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getListRuQing(int in0,int in1) { 
        LOG.info("Executing operation getListRuQing");
        System.out.println(in0);
        System.out.println(in1);
        try {
            cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean _return = new cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean();
            java.util.List<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean> _returnProcInfoBean = new java.util.ArrayList<cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean>();
            cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean _returnProcInfoBeanVal1 = new cn.gov.laho.gzfgoa.flow.webservice.ProcInfoBean();
            _returnProcInfoBeanVal1.setActId(Integer.valueOf(-1136165516));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ActName = null;
            _returnProcInfoBeanVal1.setActName(_returnProcInfoBeanVal1ActName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Coding = null;
            _returnProcInfoBeanVal1.setCoding(_returnProcInfoBeanVal1Coding);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowNum = null;
            _returnProcInfoBeanVal1.setComeFlowNum(_returnProcInfoBeanVal1ComeFlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ComeFlowOrg = null;
            _returnProcInfoBeanVal1.setComeFlowOrg(_returnProcInfoBeanVal1ComeFlowOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Compdatestr = null;
            _returnProcInfoBeanVal1.setCompdatestr(_returnProcInfoBeanVal1Compdatestr);
            _returnProcInfoBeanVal1.setCountnum(Integer.valueOf(765657422));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DataLink = null;
            _returnProcInfoBeanVal1.setDataLink(_returnProcInfoBeanVal1DataLink);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DirectOrg = null;
            _returnProcInfoBeanVal1.setDirectOrg(_returnProcInfoBeanVal1DirectOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Docket = null;
            _returnProcInfoBeanVal1.setDocket(_returnProcInfoBeanVal1Docket);
            _returnProcInfoBeanVal1.setDsmId(Integer.valueOf(1502067367));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmName = null;
            _returnProcInfoBeanVal1.setDsmName(_returnProcInfoBeanVal1DsmName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1DsmValue = null;
            _returnProcInfoBeanVal1.setDsmValue(_returnProcInfoBeanVal1DsmValue);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FileNum = null;
            _returnProcInfoBeanVal1.setFileNum(_returnProcInfoBeanVal1FileNum);
            _returnProcInfoBeanVal1.setFlag(Integer.valueOf(-1558718643));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowBjck = null;
            _returnProcInfoBeanVal1.setFlowBjck(_returnProcInfoBeanVal1FlowBjck);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowEndTime = null;
            _returnProcInfoBeanVal1.setFlowEndTime(_returnProcInfoBeanVal1FlowEndTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLbyj = null;
            _returnProcInfoBeanVal1.setFlowLbyj(_returnProcInfoBeanVal1FlowLbyj);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowLdps = null;
            _returnProcInfoBeanVal1.setFlowLdps(_returnProcInfoBeanVal1FlowLdps);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowNum = null;
            _returnProcInfoBeanVal1.setFlowNum(_returnProcInfoBeanVal1FlowNum);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsld = null;
            _returnProcInfoBeanVal1.setFlowPsld(_returnProcInfoBeanVal1FlowPsld);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowPsly = null;
            _returnProcInfoBeanVal1.setFlowPsly(_returnProcInfoBeanVal1FlowPsly);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowStartTime = null;
            _returnProcInfoBeanVal1.setFlowStartTime(_returnProcInfoBeanVal1FlowStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1FlowTitle = null;
            _returnProcInfoBeanVal1.setFlowTitle(_returnProcInfoBeanVal1FlowTitle);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Flowztc = null;
            _returnProcInfoBeanVal1.setFlowztc(_returnProcInfoBeanVal1Flowztc);
            _returnProcInfoBeanVal1.setFormId(Integer.valueOf(-552019564));
            _returnProcInfoBeanVal1.setId(Integer.valueOf(-1195968917));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhOrg = null;
            _returnProcInfoBeanVal1.setJbxhOrg(_returnProcInfoBeanVal1JbxhOrg);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1JbxhUserName = null;
            _returnProcInfoBeanVal1.setJbxhUserName(_returnProcInfoBeanVal1JbxhUserName);
            javax.xml.bind.JAXBElement<cn.gov.laho.gzfgoa.flow.webservice.ArrayOfString> _returnProcInfoBeanVal1List = null;
            _returnProcInfoBeanVal1.setList(_returnProcInfoBeanVal1List);
            _returnProcInfoBeanVal1.setNum(Integer.valueOf(890113384));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1OrgName = null;
            _returnProcInfoBeanVal1.setOrgName(_returnProcInfoBeanVal1OrgName);
            _returnProcInfoBeanVal1.setProcId(Integer.valueOf(1539681811));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ProcName = null;
            _returnProcInfoBeanVal1.setProcName(_returnProcInfoBeanVal1ProcName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Psjld = null;
            _returnProcInfoBeanVal1.setPsjld(_returnProcInfoBeanVal1Psjld);
            _returnProcInfoBeanVal1.setPsjldId(Integer.valueOf(-482588534));
            _returnProcInfoBeanVal1.setPublicAreaId(Integer.valueOf(-816763445));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceiveDataStr = null;
            _returnProcInfoBeanVal1.setReceiveDataStr(_returnProcInfoBeanVal1ReceiveDataStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStr = null;
            _returnProcInfoBeanVal1.setReceivedateStr(_returnProcInfoBeanVal1ReceivedateStr);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1ReceivedateStrend = null;
            _returnProcInfoBeanVal1.setReceivedateStrend(_returnProcInfoBeanVal1ReceivedateStrend);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Reserve = null;
            _returnProcInfoBeanVal1.setReserve(_returnProcInfoBeanVal1Reserve);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1SelectYear = null;
            _returnProcInfoBeanVal1.setSelectYear(_returnProcInfoBeanVal1SelectYear);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Senddate = null;
            _returnProcInfoBeanVal1.setSenddate(_returnProcInfoBeanVal1Senddate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Sendor = null;
            _returnProcInfoBeanVal1.setSendor(_returnProcInfoBeanVal1Sendor);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1State = null;
            _returnProcInfoBeanVal1.setState(_returnProcInfoBeanVal1State);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Title = null;
            _returnProcInfoBeanVal1.setTitle(_returnProcInfoBeanVal1Title);
            _returnProcInfoBeanVal1.setTypeId(Integer.valueOf(-656165659));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1Unit = null;
            _returnProcInfoBeanVal1.setUnit(_returnProcInfoBeanVal1Unit);
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UrgencyFlag = null;
            _returnProcInfoBeanVal1.setUrgencyFlag(_returnProcInfoBeanVal1UrgencyFlag);
            _returnProcInfoBeanVal1.setUserId(Integer.valueOf(548938302));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1UserName = null;
            _returnProcInfoBeanVal1.setUserName(_returnProcInfoBeanVal1UserName);
            _returnProcInfoBeanVal1.setWorkItemId(Integer.valueOf(219205711));
            javax.xml.bind.JAXBElement<java.lang.String> _returnProcInfoBeanVal1XbOrg = null;
            _returnProcInfoBeanVal1.setXbOrg(_returnProcInfoBeanVal1XbOrg);
            _returnProcInfoBean.add(_returnProcInfoBeanVal1);
            _return.getProcInfoBean().addAll(_returnProcInfoBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
