package cn.gov.laho.gzfgoa.flow.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Nov 07 16:59:04 CST 2014
 * Generated source version: 2.2.10
 * 
 */
 
@WebService(targetNamespace = "http://webservice.flow.gzfg.kwhope.com", name = "ProcInfoServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ProcInfoServicePortType {

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "queryFlowNum", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.QueryFlowNum")
    @WebMethod
    @ResponseWrapper(localName = "queryFlowNumResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.QueryFlowNumResponse")
    public int queryFlowNum(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in6,
        @WebParam(name = "in7", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in7,
        @WebParam(name = "in8", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in8,
        @WebParam(name = "in9", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in9,
        @WebParam(name = "in10", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in10,
        @WebParam(name = "in11", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in11,
        @WebParam(name = "in12", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in12,
        @WebParam(name = "in13", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in13
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getQueryFinishProc", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetQueryFinishProc")
    @WebMethod
    @ResponseWrapper(localName = "getQueryFinishProcResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetQueryFinishProcResponse")
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getQueryFinishProc(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in4
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getQueryFinishProcNum", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetQueryFinishProcNum")
    @WebMethod
    @ResponseWrapper(localName = "getQueryFinishProcNumResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetQueryFinishProcNumResponse")
    public int getQueryFinishProcNum(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in4
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getListRuQingNum", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListRuQingNum")
    @WebMethod
    @ResponseWrapper(localName = "getListRuQingNumResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListRuQingNumResponse")
    public int getListRuQingNum(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getListJianBao", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListJianBao")
    @WebMethod
    @ResponseWrapper(localName = "getListJianBaoResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListJianBaoResponse")
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getListJianBao(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getWeiWanDuban", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetWeiWanDuban")
    @WebMethod
    @ResponseWrapper(localName = "getWeiWanDubanResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetWeiWanDubanResponse")
    public int getWeiWanDuban(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getListProc", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListProc")
    @WebMethod
    @ResponseWrapper(localName = "getListProcResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListProcResponse")
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getListProc(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in5
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getListProcNum", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListProcNum")
    @WebMethod
    @ResponseWrapper(localName = "getListProcNumResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListProcNumResponse")
    public int getListProcNum(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in5
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "queryFlow", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.QueryFlow")
    @WebMethod
    @ResponseWrapper(localName = "queryFlowResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.QueryFlowResponse")
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean queryFlow(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in6,
        @WebParam(name = "in7", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in7,
        @WebParam(name = "in8", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in8,
        @WebParam(name = "in9", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in9,
        @WebParam(name = "in10", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in10,
        @WebParam(name = "in11", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in11,
        @WebParam(name = "in12", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in12,
        @WebParam(name = "in13", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in13,
        @WebParam(name = "in14", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in14,
        @WebParam(name = "in15", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in15
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getListProcInfo", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListProcInfo")
    @WebMethod
    @ResponseWrapper(localName = "getListProcInfoResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListProcInfoResponse")
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getListProcInfo(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getQueryProc", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetQueryProc")
    @WebMethod
    @ResponseWrapper(localName = "getQueryProcResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetQueryProcResponse")
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getQueryProc(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in3
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getQueryProcNum", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetQueryProcNum")
    @WebMethod
    @ResponseWrapper(localName = "getQueryProcNumResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetQueryProcNumResponse")
    public int getQueryProcNum(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in3
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getListJianBaoNum", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListJianBaoNum")
    @WebMethod
    @ResponseWrapper(localName = "getListJianBaoNumResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListJianBaoNumResponse")
    public int getListJianBaoNum(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getAuditDuban", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetAuditDuban")
    @WebMethod
    @ResponseWrapper(localName = "getAuditDubanResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetAuditDubanResponse")
    public int getAuditDuban(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0
    );

    @RequestWrapper(localName = "batchEditItem", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.BatchEditItem")
    @WebMethod
    @ResponseWrapper(localName = "batchEditItemResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.BatchEditItemResponse")
    public void batchEditItem(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
    @RequestWrapper(localName = "getListRuQing", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListRuQing")
    @WebMethod
    @ResponseWrapper(localName = "getListRuQingResponse", targetNamespace = "http://webservice.flow.gzfg.kwhope.com", className = "cn.gov.laho.gzfgoa.flow.webservice.GetListRuQingResponse")
    public cn.gov.laho.gzfgoa.flow.webservice.ArrayOfProcInfoBean getListRuQing(
        @WebParam(name = "in0", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.flow.gzfg.kwhope.com")
        int in1
    );
}
